### ISSUE TITLE
Big tab bar

### ISSUE THREAD

**Issue by tristan202** [Guake/guake#616] opened 2015-09-15 19:35 UTC
All of a sudden my tab bar grew to double height, and I have no way of getting it back to normal size. I tried removing everything, and reinstall from scratch, but it's still doublee size.
![untitled](https://cloud.githubusercontent.com/assets/1045501/9887778/b63815f4-5bf1-11e5-9b96-9eb61bcfadc7.png)

**Comment by Ozzyboshi** [comment] 2015-09-19 15:14
try my new data/guake.glade file (https://github.com/Ozzyboshi/guake) , i built a new virtual machine with xfce on it and it seems to work, if yes i can submit a pull request to @Stibbons on this repository

**Comment by Ozzyboshi** [comment] 2015-09-19 15:16
i think this issue is a duplicate of #599

**Closed** 2015-09-22 11:16 UTC
Labels: Priority:Low, Type: Cosmetic

**Comment by tristan202** [comment] 2015-09-22 13:20
Resolved in my end.
