### ISSUE TITLE
able to use ctrl + tab, ctrl + shift + tab as keyboard shortcut

### ISSUE THREAD

**Issue by kurokirasama** [Guake/guake#1886] opened 2021-09-10 03:52 UTC
Right now, if I try to set up this shortcut, nothing happened and the shortcut stays empty.
I'm using guake from ubuntu 20.04 repo

**Comment by Davidy22** [comment] 2021-09-10 06:51
Closing because duplicate of #152, but it is an issue I'm interested in clearing off. If you have additional information to contribute, you can add it as a comment there.

**Closed** 2021-09-10 06:51 UTC
