### ISSUE TITLE
Change dropdown animation to be like quake?

### ISSUE THREAD

**Issue by cruftytheclown** [Guake/guake#904] opened 2017-02-02 08:32 UTC
I'm on mint cinnamon 18.1, and when I open guake it has an animation where it appears in the top middle of the screen and then quickly zooms and grows to fill the top half of the screen.

I want it to simply drop down like the way the quake console does in quake. Is there a way I can make it do that?

**Comment by Stibbons** [comment] 2017-02-03 16:14
The animation is not handled by guake itself, it comes from your window manager. I'll try to make it more flexible on the next version of guake

**Comment by kwill** [comment] 2017-05-25 13:32
Duplicate of https://github.com/Guake/guake/issues/701 ?

**Comment by Davidy22** [comment] 2021-09-16 23:18
Closing because duplicate of #701

**Closed by Davidy22** 2021-09-16 23:18 UTC
