### ISSUE TITLE
Keyboard layout in wayland

### ISSUE THREAD

**Issue by fpiecka** [Guake/guake#2231] opened 2024-03-13 08:21 UTC
When guake is hidden and opened again, it's keyboard layout is reset to default in wayland. In X, keyboard layout stayed the same through hiding and reopening.

This is relevant when keyboard layout is set per window and not globally for all windows.

I understand this has something to do with window management in wayland and maybe there is no possibility of fixing this on the side of guake.

The behavior is the same in yakuake and tilda - X is ok, wayland not.

**Expected behavior**

When keyboard layouts are configured per windows in system settings, I expect guake to preserve keyboard layout setting through hiding guake and reopening it.

**Actual behavior**

Keyboard layout after reopening guake is the default. The same as for any new window.

**To Reproduce**

 Set keyboard layout switching policy to "per window" in system settings
1. Open guake and change keyboard layout to a different one from default
2. Hide guake
3. Reopen guake

**Comment by Davidy22** [comment] 2024-06-02 16:54
If this behavior occurs across multiple terminal emulators, the problem is very likely either in the wayland, which seems to frequently be the case, or in VTE, which I suspect isn't the case here because I don't think VTE has anything to the way that you're setting keyboard layouts. Closing unless demonstrated that the issue is caused by Guake code.

**Closed by Davidy22** 2024-06-02 16:54 UTC
