### ISSUE TITLE
Guake window follows mouse across monitors till it loses focus

### ISSUE THREAD

**Issue by blacktav** [Guake/guake#1738] opened 2020-03-19 23:59 UTC
**Describe the bug**

With preferences set as "Appear on Mouse Display"

After the guake window opens with focus on the monitor containing the mouse; the guake window then follows the mouse across other monitors

If guake loses focus, window no longer follows mouse but focus must go to another window on the same monitor.

Behaviour does not occur on workspaces with no open windows

**Expected behavior**

The window should NOT follow the mouse

**Work-around**

Removing the commit [5205ce2](https://github.com/Guake/guake/commit/5205ce2b3360d19e1a53a7996c502a33a435f794) as described in Issue #1720 corrects this behaviiour though clearly might have other effects

-------------------------------------------------------------------------------

Platform ArchLinux

Guake Version:		3.7.0
Vte Version:		0.60.0
Vte Runtime Version:	0.60.0
--------------------------------------------------
GTK+ Version:		3.24.14
GDK Backend:		GdkX11.X11Display
--------------------------------------------------
Desktop Session: xfce
--------------------------------------------------
Display: :0.0

RGBA visual: True

Composited: True

* Monitor: 0 - IVM DP1
    * Geometry:		1080 x 1920 at 1080, 0
    * Size:		520 x 290 mm²
    * Primary:		True
    * Refresh rate:	60.00 Hz
    * Subpixel layout:	unknown
* Monitor: 1 - IVM HDMI1
    * Geometry:		1080 x 1920 at 0, 0
    * Size:		520 x 290 mm²
    * Primary:		False
    * Refresh rate:	60.00 Hz
    * Subpixel layout:	unknown

**Comment by InFerYes** [comment] 2020-03-30 07:37
I believe I have the same issue. I have 3 monitors, and when I used to drop Guake on the left monitor to work on the center it used to stay there, but now it pops up on the monitor where I click the mouse. Once Guake lost its focus it will stay, but accidentally selecting it while tabbing will make Guake appear on the monitor with the mouse again.

**Comment by piszczek** [comment] 2020-03-30 13:10
this is most irritating thing after update;

I downgraded version till this will be fixed ;(

**Comment by iconoclasthero** [comment] 2020-04-20 15:26
So I think I'm experiencing the same issue.  Here's what happens:
1 With mouse on screen 1, hit F12 to open on screen 1.   << Guake opens on screen 1 >>
2  Move mouse to screen 2.  << Guake stays on screen 1 >>
3  Click on screen 2.  << Guake moves to screen 2 >>
4  Click back on screen 1 and leave mouse there.  << Guake stays on screen 2 >>
5  Hit F12.  << Guake is hidden >>
6  Hit F12.  << Guake is shown on screen 1 >>

If I modify that progression:
1 With mouse on screen 1, hit F12 to open on screen 1.   << Guake opens on screen 1 >>
**1.5 Clock on screen 1. << Guake remains open on screen 1 >>
2  Move mouse to screen 2.  << Guake stays on screen 1 >>
3  Click on screen 2.  << Guake remains on screen 1 >>
4  Click back on screen 1 and leave mouse there.  << Guake stays on screen 1 >>
5  Hit F12.  << Guake is hidden >>
6  Hit F12.  << Guake is shown on screen 1 >>

Is this the same behavior?  I'm having another multi-monitor issue but it might be related.

**Comment by GuzTech** [comment] 2020-05-10 11:28
I can confirm that I have the exact same issue as @iconoclasthero described above.

**Comment by justinfx** [comment] 2020-06-21 01:18
Confirming same issue on Ubuntu 20.04
Guake Version:		3.7.0

Disabling the Appear on mouse display option is not an acceptable option since one usually wants it to appear in the context of the mouse. But a visible terminal should not then start following the mouse. Even the workaround of clicking to focus another window in the same display first, before clicking into another display isn't really easy to remember to do every time. A fix is very much appreciated!

**Comment by stiltr** [comment] 2020-12-09 05:07
I applied PR #1774 and that seems to have fixed the problem for me.
I just modified util.py and restarted guake. For me it was located at /usr/lib/python3.7/site-packages/guake/utils.py, but it will probably depend on your distro.

**Comment by Davidy22** [comment] 2021-09-13 04:48
#1774 was closed, but an equivalent #1775 was merged that fixes this so closing this issue.

**Closed** 2021-09-13 04:49 UTC
