### ISSUE TITLE
Need a new release since the search is broken in 3.7.0

### ISSUE THREAD

**Issue by bucknerns** [Guake/guake#1839] opened 2021-04-02 20:30 UTC
Be sure to check the existing issues (both open and closed!), and make sure you are running the latest version of Guake.

For how to run the latest Guake in your computer, please refer to [Install from source](https://guake.readthedocs.io/en/latest/user/installing.html#install-from-source).

---------------------------------------

Please use [FeatHub](https://feathub.com/Guake/guake) to fill-up a feature request.

This allow us to spot directly which are the most requested features.

**Comment by Davidy22** [comment] 2021-09-04 03:13
Closing because duplicate of #1802

**Closed by Davidy22** 2021-09-04 03:13 UTC
