### ISSUE TITLE
Scrollbar Hidden Resize Issues

### ISSUE THREAD

**Issue by aero31aero** [Guake/guake#1332] opened 2018-05-21 19:07 UTC
I have scrollbar disabled in the settings, but it seems to render and then disappear from the screen on opening guake.

In a normal theme, it should be fine, but in tmux with panes, this causes a weird flicker behavior where the divider shifts one unit to the right immediately after opening guake.

Can confirm its an issue with scrollbar appearing and hiding because on enabling scrollbar there is no fluctuation in screen width with guake.

  - **Guake Version**: Guake Terminal 3.0.5
  - Ubuntu Mate 18.04, Gnome shell not installed.
  - GTK Versions: libgtk-3-0:amd64  3.22.30-1ubuntu1 amd64, libgtk2.0-0:amd64 2.24.32-1ubuntu1 amd64

**Comment by aichingm** [comment] 2018-08-24 21:11
*I can't reproduce this issue with guake version 3.3.2 nor HEAD.*

What hardware are you running?
There is a PR open at the moment #1385 which changes a lot of the code involved this the layout of the widgets (and scrollbars) could you check if this issue also happens after this commit: 2696bc85f0023c8eb376f093720717f0ea15763c

**Comment by Davidy22** [comment] 2022-04-20 03:59
Closing because render issue on Guake prior to a gtk upgrade

**Closed by Davidy22** 2022-04-20 03:59 UTC
