### ISSUE TITLE
Sometimes renders as only a grey rectangle

### ISSUE THREAD

**Issue by schnittchen** [Guake/guake#454] opened 2015-01-28 09:04 UTC
Hi there,

guake sometimes falls into this weird mode which I cannot get it out of, except by quitting it.
This seems to happen when toggling visibility when there is a lot of contention.

The symptom is that the entire guake window, including all chrome and borders, is just flat grey.
I can still pop up the context menu to open a new tab or rename a tab or show the settings. The mouse face is still changed depending on the region of the window I hover over. I can still type commands (like xdg-open, to see the effect).

I have not found any way for guake to re-draw the window properly.

**Comment by kuggagrun** [comment] 2015-02-12 20:59
I can confirm this, exactly like schnittchen said.  Using Ubuntu 14.04 with Unity.

**Comment by wvanlint** [comment] 2015-02-13 06:48
I seem to be able to reproduce this consistently by holding my shortcut for toggling visibility, making guake rapidly hide and appear again. After a second or so, the window will render as the described grey rectangle.

**Comment by schnittchen** [comment] 2015-02-13 19:24
@wvanlint also on unity?

**Comment by wvanlint** [comment] 2015-02-14 05:34
Yes, using Ubuntu 14.10 with Unity.

**Comment by jseidel** [comment] 2015-03-26 14:07
I have the same issue with xfce on xubuntu 14.04.2 (xfce window manager) and guake 0.4.4. This appears to happen regularly after changing the monitor layout.

**Comment by Davidy22** [comment] 2021-09-16 22:18
Since the last reproduction, guake has been ported to gtk 3 and I cannot reproduce by following the given steps. Does this still occur for the affected people?

**Comment by schnittchen** [comment] 2021-09-17 13:20
I haven't had this issue in a long time

**Comment by Davidy22** [comment] 2021-09-17 14:00
Alright. I do believe the port to gtk3 should have cleared up any of the rendering bugs specific to gtk2, even if it brought new ones, will close this since this was probably incidentally fixed by the move to gtk3

**Closed by Davidy22** 2021-09-17 14:00 UTC
Labels: Type: Defect, Priority: Low
