### ISSUE TITLE
Guake always appears on mouse display regardless of Guake Preferences

### ISSUE THREAD

**Issue by givascu** [Guake/guake#1689] opened 2019-12-06 11:56 UTC
**Describe the bug**

Guake appears on mouse display even though "always on primary" option is checked in Guake Preferences -> Main Window -> Placement -> Appear on display. Same thing happens when "0 (primary)" option is checked. These options seem to have no effect.

**Expected behavior**

Guake should appear on primary display, as per the checked option in Guake Preferences.

**Actual behavior**

Guake appears on mouse display regardless of what is checked in Guake Preferences.

**To Reproduce**

1. Go to Guake Preferences -> Main Window -> Placement -> Appear on display.
2. Toggle each option, one at a time.
3. Use the "Toggle Guake visibility" keyboard shortcut to open Guake. 
4. Guake appears on mouse display everytime. The "Appear on display" options in Guake Preferences seem to have no effect on Guake's behavior.

-------------------------------------------------------------------------------

<details><summary>$ guake --support</summary>

Guake Version:		3.6.3

Vte Version:		0.58.3

Vte Runtime Version:	0.58.3

--------------------------------------------------
GTK+ Version:		3.24.13

GDK Backend:		__gi__.GdkWaylandDisplay

--------------------------------------------------
Desktop Session: gnome

--------------------------------------------------
Display: wayland-0

RGBA visual: True

Composited: True

* Monitor: 0 - BOE 0x06ee
    * Geometry:		1920 x 1080 at 0, 1200
    * Size:		310 x 170 mm²
    * Primary:		False
    * Refresh rate:	60.01 Hz
    * Subpixel layout:	unknown
* Monitor: 1 - DEL DELL U2415
    * Geometry:		1920 x 1200 at 0, 0
    * Size:		520 x 320 mm²
    * Primary:		False
    * Refresh rate:	59.95 Hz
    * Subpixel layout:	unknown

**Comment by OmerSakar** [comment] 2019-12-17 12:24
Although not exactly the same issue, I think my issue is related to this one. 

I have the option to appear on mouse display enabled. I have a two-monitor setup and my mouse is on one of the two screens. I open Guake on one screen and move my mouse to the other screen. When I click on a window on the other screen Guake jumps to that screen. If I then click on the first screen, it does not jump back.

Another case: If I open Guake, then click on a window on the same screen and then click on a window on the other screen, it does not jump to that screen.

I would guess that `appear on mouse display` is supposed to open on the screen where your mouse is and **stay there**.

The output of `guake --support` below:
> Guake Version:		3.6.3
> Vte Version:		0.52.2
> Vte Runtime Version:	0.52.2
>
> GTK+ Version:		3.22.30
> GDK Backend:		GdkX11.X11Display
> 
> Desktop Session: ubuntu
> 
> Display: :0
> RGBA visual: True
> Composited: True
> * Monitor: 0 -  DP-1
>     * Geometry:		2560 x 1600 at 1920, 0
>     * Size:		641 x 401 mm²
>     * Primary:		True
>     * Refresh rate:	59.86 Hz
>     * Subpixel layout:	unknown
> * Monitor: 1 -  eDP-1
>     * Geometry:		1920 x 1080 at 0, 520
>     * Size:		344 x 193 mm²
>     * Primary:		False
>     * Refresh rate:	60.06 Hz
>     * Subpixel layout:	unknown

**Comment by simonCor** [comment] 2019-12-23 09:45
I have the same problem - guake always appears on mouse display - although it is configured to always appear on a specific display.

output of guake --support:
```
Guake Version:		3.6.3

Vte Version:		0.58.3

Vte Runtime Version:	0.58.3

--------------------------------------------------
GTK+ Version:		3.24.13

GDK Backend:		GdkX11.X11Display

--------------------------------------------------
Desktop Session: gnome

--------------------------------------------------
Display: :0

RGBA visual: True

Composited: True

* Monitor: 0 -  XWAYLAND0
    * Geometry:		1920 x 1080 at 1920, 0
    * Size:		480 x 270 mm²
    * Primary:		True
    * Refresh rate:	59.96 Hz
    * Subpixel layout:	unknown
* Monitor: 1 -  XWAYLAND1
    * Geometry:		1920 x 1080 at 0, 0
    * Size:		480 x 270 mm²
    * Primary:		False
    * Refresh rate:	59.96 Hz
    * Subpixel layout:	unknown
```

**Comment by NingPing** [comment] 2020-01-04 15:03
Can reproduce this issue on guake v 3.6.3 on linux mint xfce
If you set in Geometry the max height and width and then restart guake it will now display on mouse even though its not activated 
drag height or width to any other then max will work for me, even after restart

**Comment by simonCor** [comment] 2020-01-08 08:46
Hmmm i tested it. Showed another issue: The Gemoetry settings do not change anything.

Guake keeps to open in full screen no matter what is set in Geometry. (The "Start fullscreen"-option is not active).

**Comment by freimair** [comment] 2020-02-18 15:02
I just looked into it and I found that code-wise, the window position does not change at all, neither does the monitor index - it stays at the configured index. I highly suspect our wayland setups have something to do with that. I will investigate further.

<details><summary>$ guake --support</summary>

Guake Version:		3.7.1

Vte Version:		0.58.3

Vte Runtime Version:	0.58.3

--------------------------------------------------
GTK+ Version:		3.24.14

GDK Backend:		__gi__.GdkWaylandDisplay

--------------------------------------------------
Desktop Session: gnome

--------------------------------------------------
Display: wayland-0

RGBA visual: True

Composited: True

* Monitor: 0 - DEL DELL U2412M
    * Geometry:		1920 x 1200 at 3600, 0
    * Size:		520 x 320 mm²
    * Primary:		False
    * Refresh rate:	59.95 Hz
    * Subpixel layout:	unknown
* Monitor: 1 - SAM SyncMaster
    * Geometry:		1680 x 1050 at 0, 0
    * Size:		470 x 300 mm²
    * Primary:		False
    * Refresh rate:	59.88 Hz
    * Subpixel layout:	unknown
* Monitor: 2 - HWP HP LP2475w
    * Geometry:		1920 x 1200 at 1680, 0
    * Size:		540 x 350 mm²
    * Primary:		False
    * Refresh rate:	59.95 Hz
    * Subpixel layout:	unknown

**Comment by freimair** [comment] 2020-02-18 20:43
hate to do this but for all you guys having trouble with wayland and gnome-shell:

try [this shell extension](https://extensions.gnome.org/extension/1411/quake-mode/) and [terminator](https://terminator-gtk3.readthedocs.io/en/latest/)

**Comment by gabrielivascu** [comment] 2020-02-19 08:26
> try this [shell extension](https://extensions.gnome.org/extension/1411/quake-mode/) and [terminator](https://terminator-gtk3.readthedocs.io/en/latest/)

Is "quake-mode" extension going to work on newer versions of gnome-shell? Seems that the latest supported shell on the extensions page is only 3.30.

**Comment by simonCor** [comment] 2020-02-19 08:31
Hui thanks @freimair - this is cool and works.

I use it on gnome Version 3.34.3 - no problems.

**Comment by gchamon** [comment] 2020-05-28 15:56
I think I have it in #1765

can you guys confirm?

Just add 

`window.move(window_rect.x, window_rect.y)` before `window.maximize()` at line `267`

Reference: https://stackoverflow.com/a/39386341/3476100

**Comment by gabrielivascu** [comment] 2020-05-29 07:38
@gchamon thanks for taking the time to investigate this. I'll give it a try as soon as I get back to my dual monitor setup.

**Comment by gabrielivascu** [comment] 2020-06-16 08:00
@gchamon - sorry for taking too long to respond. I've tested your suggestion, but unfortunately, it doesn't fix the bug for me, it still reproduces. Please let me know how can I assist you further should you choose to continue investigating this.

**Comment by gabrielivascu** [comment] 2022-09-20 07:25
Coming back on this. This still happens on GNOME Shell 42.5 with Wayland as GDK backend and the following guake version:
```
$ guake --version
Guake Terminal: 3.7.0
VTE: 0.68.0
VTE runtime: 0.68.0
Gtk: 3.24.34
```

It doesn't seem to reproduce with X11 as GDK backend though.

**Comment by white-gecko** [comment] 2023-12-11 14:34
I have installed the latest guake from pip, which does not have the bug. So I think this issue is a matter of creating up to date packages for guake but not an issue in the guake source code anymore. So this could be closed.

**Comment by deivid11** [comment] 2024-01-28 19:10
> I have installed the latest guake from pip, which does not have the bug. So I think this issue is a matter of creating up to date packages for guake but not an issue in the guake source code anymore. So this could be closed.

Thanks @white-gecko, installing from pip worked for me too.

**Comment by Davidy22** [comment] 2024-05-30 12:03
Closing since this appears to just be a distribution issue.

**Closed by Davidy22** 2024-05-30 12:03 UTC
