### ISSUE TITLE
Guake window shown on the wrong monitor when monitors overlap

### ISSUE THREAD

**Issue by eric-saintetienne** [Guake/guake#1837] opened 2021-03-22 22:19 UTC
**Describe the bug**

Guake window is shown on the wrong monitor when monitors overlap.

**Expected behavior**

Guake shown on the selected monitor (or that of the mouse, if set in the preferences)

**Actual behavior**

Guake is always shown on the wrong monitor.

**To Reproduce**

Use 2 monitors horizontally, overlap the right monitor slightly to the left by one pixel.
Set guake to show on the left monitor, that works

Now to reproduce the issue, either:
- Set guake to show on the right monitor but guake will always show on the left monitor
    or
- Set "follow the mouse" and leave the mouse on the right monitor, toggle Guake visibility and it will always be displayed on the left monitor.

-------------------------------------------------------------------------------

I have two 1920x1080 monitors aligned horizontally.
The right-most monitor is starting at offset 1919 (not 1920) thus causing an overlap of 1 pixel.
I use the feature where Guake follows the mouse (it shows on the display where the mouse is)

Guake is always showing on the left monitor. Despite this 1 pixel overlap between the 2 monitors, the Guake window should appear on the monitor where the mouse is... but it doesn't!

Instead of using the mouse coordinates, Guake seems to determine that the mouse is on the right-most monitor, then fetch the pixel location of the top-left corner of that monitor (pixel X=1919), then resolve again the monitor to find that it's the left-most monitor that contains that pixel, and hence show Guake window on the left-most monitor.

So this fails (Guake window is always shown on the left-most monitor)

<details><summary>$ guake --support</summary>

Guake Version:		3.6.3

Vte Version:		0.62.3

Vte Runtime Version:	0.62.3

--------------------------------------------------
GTK+ Version:		3.24.27

GDK Backend:		GdkX11.X11Display

--------------------------------------------------
Desktop Session: /usr/share/xsessions/plasma

--------------------------------------------------
Display: :0

RGBA visual: True

Composited: True

* Monitor: 0 - LEN HDMI-2
    * Geometry:		1920 x 1080 at 0, 0
    * Size:		527 x 296 mm²
    * Primary:		True
    * Refresh rate:	60.00 Hz
    * Subpixel layout:	unknown
* Monitor: 1 - LEN DP-2
    * Geometry:		1920 x 1080 at 1919, 0
    * Size:		527 x 296 mm²
    * Primary:		False
    * Refresh rate:	60.00 Hz
    * Subpixel layout:	unknown
</details>

But this works (Guake window is shown on the correct monitor):

<details><summary>$ guake --support</summary>

Guake Version:		3.6.3

Vte Version:		0.62.3

Vte Runtime Version:	0.62.3

--------------------------------------------------
GTK+ Version:		3.24.27

GDK Backend:		GdkX11.X11Display

--------------------------------------------------
Desktop Session: /usr/share/xsessions/plasma

--------------------------------------------------
Display: :0

RGBA visual: True

Composited: True

* Monitor: 0 - LEN HDMI-2
    * Geometry:		1920 x 1080 at 0, 0
    * Size:		527 x 296 mm²
    * Primary:		True
    * Refresh rate:	60.00 Hz
    * Subpixel layout:	unknown
* Monitor: 1 - LEN DP-2
    * Geometry:		1920 x 1080 at 1920, 0
    * Size:		527 x 296 mm²
    * Primary:		False
    * Refresh rate:	60.00 Hz
    * Subpixel layout:	unknown
</details>

**Comment by eric-saintetienne** [comment] 2021-05-04 03:54
Any news on this issue?

**Comment by figure002** [comment] 2021-08-07 01:38
This issue happens even without the 1 pixel overlap:

<details><summary>$ guake --support</summary>

Guake Version:		3.6.3

Vte Version:		0.62.3

Vte Runtime Version:	0.62.3

--------------------------------------------------
GTK+ Version:		3.24.25

GDK Backend:		__gi__.GdkWaylandDisplay

--------------------------------------------------
Desktop Session: ubuntu

--------------------------------------------------
Display: wayland-0

RGBA visual: True

Composited: True

* Monitor: 0 - IVM PL2760Q
    * Geometry:		2560 x 1440 at 1920, 0
    * Size:		600 x 340 mm²
    * Primary:		False
    * Refresh rate:	59.95 Hz
    * Subpixel layout:	unknown
* Monitor: 1 - DEL DELL P2417H
    * Geometry:		1920 x 1080 at 0, 0
    * Size:		530 x 300 mm²
    * Primary:		False
    * Refresh rate:	60.00 Hz
    * Subpixel layout:	unknown
</details>

This has become an issue since switching to Wayland.

**Comment by Davidy22** [comment] 2021-09-13 04:46
A patch that may fix this has just been merged. Can you confirm whether or not this is fixed in the current git main? If you can't compile, updates when the next version is released are also welcome.

**Comment by Killea** [comment] 2022-05-02 15:59
same issue when using wayland. 
this is related to the setting ' Appear on mouse display'. if you open an application on the monitor and set focus to the monitor, guake can show up correctly, but this is definitely a bug and need to be fixed. thank you, developers.

**Comment by Davidy22** [comment] 2022-06-13 14:27
Closing since reported fixed by a reproducer

**Closed by Davidy22** 2022-06-13 14:27 UTC

**Comment by figure002** [comment] 2022-06-13 19:46
Thanks for fixing @Davidy22 !
