### ISSUE TITLE
Hide Guake instead of focus

### ISSUE THREAD

**Issue by austinjdean** [Guake/guake#1029] opened 2017-11-20 16:10 UTC
### Settings:
`Stay on top` is **enabled**.
`Hide on lose focus` is **disabled**.

### Behavior:
- I toggle visibility and Guake appears.
- Then I interact with another window behind Guake. Guake stays on top but loses focus as expected.
- Then I wish to dismiss Guake, so I toggle visibility again.
- This brings the focus back to Guake instead of toggling visibility. Then I must toggle visibility again while Guake is focused to dismiss the terminal.

I would prefer the "toggle visibility" key to toggle Guake's visibility regardless of its focus status, if `hide on lose focus` is not enabled.

OS: both Ubuntu 16.04 and Kali

**Comment by aichingm** [comment] 2017-11-22 08:52
Disable the "Refocus if open" option.
I think this option is available since guake 8.11 or if you install guake from commit 8bcb361e8fe4d75f77c61b86fc1e5112e65795b0  or above.

![screenshot_20171122_094538](https://user-images.githubusercontent.com/6470959/33117751-e97a53c6-cf69-11e7-82aa-96b9dc02cd62.png)

**Comment by aichingm** [comment] 2017-11-22 08:55
This is a duplicate of #976 and is fixed in #977.
@austinjdean as the issue says you could also down grade to 0.8.8

**Closed** 2017-11-22 11:20 UTC
