### ISSUE TITLE
ctrl + shift + w, closing, and exit cmd

### ISSUE THREAD

**Issue by ghost** [Guake/guake#1472] opened 2018-12-13 06:32 UTC
Similar to #769, #548 - 

> side note: running "exit" does not close tab (just sits there)

open two tabs, write a sentence in one (don't press enter), close the other tab, and it'll delete the last word in the sentence.

**Comment by CottonEaster** [comment] 2018-12-15 14:01
Yep, same here.

**Comment by aichingm** [comment] 2019-01-04 14:04
I'm having trouble to reproduce this issue. `exit` is working too. 

what versions are you guys using?

**Comment by toxik-io** [comment] 2019-01-07 04:10
guake 3.0.5
bash 4.4.19
ubuntu 18.04 (was linux mint at the time of the bug)

**Comment by toxik-io** [comment] 2019-01-07 04:10
have two terminals open and type exit on one of them.

**Comment by rhwendt** [comment] 2019-02-04 21:38
ctrl + shift + w not working on fresh antergos install  running in X11

Name            : guake
Version         : 3.4.0-1
Shell: zsh 5.7
OS: Antergos Linux x86_64 
Kernel: 4.20.6-arch1-1-ARCH

**Comment by tallanvor** [comment] 2019-02-18 21:49
Has same problem with tab closing

Name : guake
Version : 3.4.0
Shell: bash 5.0.0
OS: Antergos Linux x86_64
Kernel: 4.20.8-arch1-1-ARCH

P.S. Installation not fresh, but global updated

**Comment by Mayurifag** [comment] 2019-03-01 02:24
archlinux, latest guake + cinnamon, default settings ctrl+shift+w doesn't close tab

**Comment by toxik-io** [comment] 2019-03-03 04:35
would it be helpful to split this into separate bugs?

1. exit cmd and then trying to issue the ctrl/shift/w exit shortcut
2. exit cmd and then trying to issue ctrl shift q exit shortcut
3. exit cmd and trying to create a new tab (Within that dead tab)
4. word-deletion across multiple tabs when deleting a tab

I realize it might be keyboard shortcuts, but does the program have a way to respond to a dead tab if there's no bash to send keyboard shortcuts to (if you see where I'm going with this?)

as far as word deletion, maybe it could be keyboard shortcuts and that's just a way to delete chars?

:/ puzzled.

**Comment by toxik-io** [comment] 2019-03-05 04:50
Interestingly, the word-deletion appears to be /wherever the cursor was/ in the sentence of the tab you arrive at, when closing one.

**Comment by Goutte** [comment] 2019-05-18 11:08
Confirming this bug is still rocking on guake 3.4.0  (from Kubuntu 19.04)

Workarounds:  `Meta+X` or `Ctrl+D`, but muscle memory is protesting.

**Comment by mlouielu** [comment] 2019-05-19 07:36
@Goutte Could you run [with latest version of guake from source code](http://guake.readthedocs.io/en/latest/user/installing.html#install-from-source) and test it again?

**Comment by Goutte** [comment] 2019-05-19 07:50
Thanks @mlouielu for the handy link to the doc!
The bootstrap script makes it easy to install from source.

I can confirm that with the latest master, closing with `Ctrl+Shift+W` works as expected!

**Comment by gsemet** [comment] 2019-05-20 14:35
cool :) so we can close this ticket?

**Comment by Goutte** [comment] 2019-05-20 14:42
@gsemet The collision between `Ctrl+Shift+W` (close tab) and `Ctrl+W` (delete last word) is still happening. Closing a tab is going to delete the last word in the tab getting the focus.

It's a minor bug, but it's still not the expected behavior.

**Comment by mlouielu** [comment] 2019-05-24 03:31
@Goutte I just reproduce it on master `HEAD`

reproduce:
1. open one tab, type `foo bar`
2. open another tab, then `Ctrl+Shift+W` on it
3. re-focus to first tab, but the word last to `foo` only.

**Comment by mlouielu** [comment] 2019-05-24 04:21
Let me generalize this issue: after then tab get close, re-focus tab will get the keypress event:

* 1 tab: 0x55b95ddcd310
* 2 tab: 0x55b95ed74170

When doing `Ctrl + Shift + W`, the keypress event give us:
```
<... (guake+terminal+GuakeTerminal at 0x55b95ed74170)>       # Second tab
Control_L <flags GDK_SHIFT_MASK of type Gdk.ModifierType> <flags 0 of type Gdk.ModifierType>
<..(guake+terminal+GuakeTerminal at 0x55b95ddcd310)>         # First tab
W <flags GDK_SHIFT_MASK of type Gdk.ModifierType> <flags GDK_CONTROL_MASK of type Gdk.ModifierType>
```

That the first tab get the W+Ctrl+Shift for some reason.

Thus we can generalize this issue to, if someone put `Ctrl + Shift + a` to `close-tab`, it will then move the cursor to the start of the line (since `Ctrl + a` will move cursor to start of the line)

**Comment by mlouielu** [comment] 2019-05-24 04:23
This issue was not found at terminator or tilix, so it should able be fixed on guake. If anyone want to help on this issue, I can take some help on it. (Just did the small try, but I got no time for this issue at this moment)

**Comment by mlouielu** [comment] 2019-05-24 04:49
NOTE: this didn't affect on the split terminal (e.g. close terminal set to `Ctrl+Shift+W` then do the same thing in split terminal)

**Comment by libook** [comment] 2019-07-16 08:32
@mlouielu Hi, is there a version released? Wish I can see it solved on Arch Linux. Thanks!

**Comment by libook** [comment] 2019-07-16 11:13
@mlouielu I can wait for release. Thanks for your replying!

**Comment by zenmasterjobo** [comment] 2019-08-22 06:14
Hey I am going to give this a shot at fixing it, I have not worked on this code base before - but will open a PR if I get anywhere, in the mean time, any advice or tips on where I should start looking would be super appreciated @mlouielu :)

**Comment by mlouielu** [comment] 2019-08-22 07:08
@zenmasterjobo Great, would you like to take a look into the [build from source](https://guake.readthedocs.io/en/latest/user/installing.html#install-from-source) and test if you can run it.

Then take a look into [running GTK+ applications](https://developer.gnome.org/gtk3/stable/gtk-running.html) to see how to use the debug infra for GTK+ application. (e.g. `GTK_DEBUG=interactive make run`)

Since is a while, I don't sure where this bug locate from, but you can start from  `terminal.py:GuakeTerminal` to check how the hotkey works.

**Comment by zenmasterjobo** [comment] 2019-09-06 07:02
@mlouielu Hey, thanks for the information and pointing me in a good direction

After going through the 'build from source' link and not having any issues I then followed this link: https://guake.readthedocs.io/en/latest/contributing/dev_env.html

and pretty much no matter how I install - when I run `make run` I get this error `ModuleNotFoundError: No module named 'gi'`

have you gotten this error before? Any idea what this is indicative of?

Thanks for your help!

**Comment by gkochyli** [comment] 2020-10-04 16:43
Hi, I want to give this a shot. I got familiar with the code and tried some stuff with no success.I would like some tips as to how this should be implemented. Thanks

**Comment by Davidy22** [comment] 2021-09-16 23:12
Keyboard shortcut code has been somewhat rewritten in git master. Does this still occur for the affected?

**Comment by Davidy22** [comment] 2022-06-20 16:48
Cannot reproduce with post-keybinding rework guake, closing.

**Closed by Davidy22** 2022-06-20 16:48 UTC
Labels: Priority: Low, good first issue
