### ISSUE TITLE
guake centered on screen under Gnome Wayland

### ISSUE THREAD

**Issue by lgaboury** [Guake/guake#1583] opened 2019-05-05 15:04 UTC
System: Acer laptop E5-575G (no external monitor connected)
Distro: Arch Linux
Gnome Shell: 3.32.1
Wayland: 1.17.0
Guake version: 3.6.1 or 3.6.2

guake drop down terminal displays in the center of the screen under gnome wayland if gnome tweaks "Center New Windows" is enabled under the Windows tab.
![center_new_windows](https://user-images.githubusercontent.com/50297059/57195656-c5cead80-6f1a-11e9-8fba-7924a2c4bf4c.png)
![guake_in_middle](https://user-images.githubusercontent.com/50297059/57195657-c5cead80-6f1a-11e9-9ba1-e4dc1b8d3ae7.png)
With "Center New Windows" enabled, the quake preferences for Geometry under Main Window have no effects.

![guake_prefs](https://user-images.githubusercontent.com/50297059/57195786-27dbe280-6f1c-11e9-8b5f-32a9565eeee1.png)

For the guake properties selected in the above screenshot, I believe the terminal should still be displayed at the top.

I have tested this under gnome Xorg with the same guake preferences and with Tweaks "Center New Windows" enabled, the terminal is displayed at the top as one would expect.

Under Arch Linux, reverting the guake package back to version 3.5.0 brought back the correct/expected behavior under gnome wayland.

**Comment by mlouielu** [comment] 2019-05-05 15:19
Could you help to do git bisect to figure out which commit causing this
regression?


Thanks.

lgaboury <notifications@github.com> 於 2019年5月5日 週日 23:09 寫道：

**Comment by lgaboury** [comment] 2019-05-05 16:13
I'd be happy to assist although I am not familiar with the git bisect process other than what I just read on the Git Docs.  I would need some pointers on how to get started.

Cheers!

**Comment by mlouielu** [comment] 2019-05-05 16:32
So as the doc write: https://git-scm.com/docs/git-bisect, as you wrote, current master `HEAD` is bad, and tag 3.5.0 is good, so init bisect like this

```
$ git bisect start
$ git bisect bad
$ git bisect good 3.5.0
```

then start round to test if Guake is good or bad in each round

```
If Guake is work on this round
$ git bisect good

If Guake is bad on this round
$ git bisect bad
```

Finally you will get the commit hash of the first bad commit, please write that commit here, and do `git bisect reset` to end bisect!

**Comment by lgaboury** [comment] 2019-05-05 17:34
Here is the result of git bisect:

9b2f85ee5feb62ac36079664a12ddf1586a56d99 is the first bad commit
commit 9b2f85ee5feb62ac36079664a12ddf1586a56d99
Author: Louie Lu <git@louie.lu>
Date:   Sat Apr 13 16:09:48 2019 +0800

    Add save/restore preferences to Guake CLI
    
        $ guake --save-preferences prefs.guake
        $ guake --restore-preferences prefs.guake
    
    **WARNING**
    
    User will need to ensure the content inside the preferences file,
    otherwise it may broke up the preferences, e.g. bad accel-key binding

:040000 040000 2f833bc4cc45f422dc34d5d3b0a1505ba20497e8 f4ea05e2d1f4e0f04e44ae25bc3bfad7a37a5a33 M	guake

**Comment by mlouielu** [comment] 2019-05-05 17:51
That's me... But why would a code that even didn't touch how the position
calculate break this?

lgaboury <notifications@github.com> 於 2019年5月6日 週一 01:34 寫道：

**Comment by lgaboury** [comment] 2019-05-05 18:15
The other thing I noticed while running through the git bisect process (which I had not noticed before) is at that same commit point guake starts but complains about key binding.  The message is:

"A problem happened when binding F12 key.  Please use Guake Prefe..."  The rest is cut off on the gnome notification popup.  This warning only starts appearing after the above commit point.

Hope this helps!

Luc Gaboury.

**Comment by lgaboury** [comment] 2019-05-05 19:12
Here is another thing.  With version 3.5.0, there **isn't** a Guake Terminal menu displayed on the Gnome Top Bar
![Guake-3 5 0](https://user-images.githubusercontent.com/50297059/57198964-ee689e80-6f3e-11e9-8525-e2152c4c81c9.png)

yet there is one after the above commit point
![guake_after_first_bad_commit](https://user-images.githubusercontent.com/50297059/57198847-66ce6000-6f3d-11e9-9766-ab171e39112f.png)

A window type issue maybe?

**Comment by mlouielu** [comment] 2019-05-06 03:07
Just a note here: [random window position with desktop shell](https://lists.freedesktop.org/archives/wayland-devel/2015-September/024451.html)

So wayland didn't have a global coordinate system, thus setting `self.window.move` and `self.window.get_position()`  will [not work at all](https://lazka.github.io/pgi-docs/#Gtk-3.0/classes/Window.html#Gtk.Window.get_position)

Also, revert the commit will causing wayland not to support transparency. (I just still can't figure out why is causing this bug at all...thought)

**Comment by mlouielu** [comment] 2019-05-06 03:28
Also for [tilix](https://gitlab.gnome.org/GNOME/mutter/issues/316) suffering this issue

**Comment by mlouielu** [comment] 2019-05-06 03:47
A workaround: [disable Wayland...](https://github.com/LearntEmail/ml-favicon/blob/5a1883682b7382eed370ab92a76da7de37347cc0/thumbnail.py#L24)

**Comment by mlouielu** [comment] 2019-05-09 07:42
GDK backend with wayland only (for sure which failed with positioning):

<details><summary>$ guake --support</summary>

Guake Version:		3.6.3

Vte Version:		0.57.1

Vte Runtime Version:	0.57.1

--------------------------------------------------
GTK+ Version:		3.24.8

GDK Backend:		__gi__.GdkWaylandDisplay

--------------------------------------------------
Desktop Session: gnome

--------------------------------------------------
Display: wayland-0

RGBA visual: True

Composited: True

* Monitor: 0 - DEL DELL U2414H
    * Geometry:		1920 x 1080 at 1920, 0
    * Size:		530 x 300 mm²
    * Primary:		False
    * Refresh rate:	60.00 Hz
    * Subpixel layout:	unknown
* Monitor: 1 - ACI ASUS PA238
    * Geometry:		1920 x 1080 at 0, 0
    * Size:		510 x 290 mm²
    * Primary:		False
    * Refresh rate:	60.00 Hz
    * Subpixel layout:	unknown

**Comment by luisnabais** [comment] 2019-05-09 08:59
I have the same issue, so here's my information:

GNOME 3.32.1 with Wayland on Arch Linux, Kernel 5.0.13.

$ guake --support
<details><summary>$ guake --support</summary>

Guake Version:		3.6.2

Vte Version:		0.56.3

Vte Runtime Version:	0.56.3

--------------------------------------------------
GTK+ Version:		3.24.8

GDK Backend:		__gi__.GdkWaylandDisplay

--------------------------------------------------
Desktop Session: gnome

--------------------------------------------------
Display: wayland-0

RGBA visual: True

Composited: True

* Monitor: 0 - HWP HP P201
    * Geometry:		1600 x 900 at 0, 0
    * Size:		440 x 250 mm²
    * Primary:		False
    * Refresh rate:	60.00 Hz
    * Subpixel layout:	unknown
* Monitor: 1 - SDC 0x4d42
    * Geometry:		1366 x 768 at 1600, 0
    * Size:		310 x 170 mm²
    * Primary:		False
    * Refresh rate:	59.99 Hz
    * Subpixel layout:	unknown

**Comment by mlouielu** [comment] 2019-05-09 09:27
@luisnabais Yes, it will, and probably be won't fix in pure Wayland backend, since Wayland didn't provide a [global/absolute] coordinate system (as a design choice). Most of the drop-down terminal suffer by this.

**Comment by lgaboury** [comment] 2019-05-09 11:35
Here is my ouptut of guake --support:

[lgaboury@Acer-E5-575G ~]$ guake --suport
Usage: guake [options]

guake: error: no such option: --suport
[lgaboury@Acer-E5-575G ~]$ guake --support
<details><summary>$ guake --support</summary>

Guake Version:		3.6.2

Vte Version:		0.56.3

Vte Runtime Version:	0.56.3

--------------------------------------------------
GTK+ Version:		3.24.8

GDK Backend:		__gi__.GdkWaylandDisplay

--------------------------------------------------
Desktop Session: gnome

--------------------------------------------------
Display: wayland-0

RGBA visual: True

Composited: True

* Monitor: 0 - BOE 0x06ba
    * Geometry:		1920 x 1080 at 0, 0
    * Size:		340 x 190 mm²
    * Primary:		False
    * Refresh rate:	60.01 Hz
    * Subpixel layout:	unknown
[lgaboury@Acer-E5-575G ~]$

**Comment by mlouielu** [comment] 2019-05-09 13:40
Interesting.... or strange....

I've get gdk backend with wayland, but DISPLAY=:0, and it works. It
shouldn't works anyway.

Still, not working in weston (as expected)

lgaboury <notifications@github.com> 於 2019年5月9日 週四 19:35 寫道：

**Comment by lgaboury** [comment] 2019-05-10 00:52
Hi Louie,

Just so you know, I do not have Weston installed on my Arch Linux system.  I'm using Gnome Mutter as the Wayland compositor.

**Comment by dakoellis** [comment] 2019-05-14 17:50
Just want to add I also ran into a similar issue.  with 3.6.1 and later, I was also getting a message saying guake can't bind to my hotkey (ctrl + `).  However my issue was that it was opening at the top, not the middle.  Downgrading to 3.5.0 got it working again how I want.

**Comment by rmeissn** [comment] 2019-09-02 10:37
Fedora recently pushed an update of Guake to v. 3.6.3 and thus introduced this issue for me.
This is very annoying and should be fixed, as it was working on a prior version.
I also enabled "Center New Windows" and am using Gnome-Shell on Wayland.

**Comment by mlouielu** [comment] 2019-09-02 11:18
@rmeissn, can you provide the last version that works under Wayland?

**Comment by rmeissn** [comment] 2019-09-02 12:06
As far as I am able to crawl the repositories, Fedora (30) initially provided version 0.8.8 and upgraded directly to version 3.6.3 a few days ago. I have downgraded to 0.8.8 again.
@lgaboury showed in his comment that version 3.5.0 worked as expected.

**Comment by soraxas** [comment] 2021-01-06 11:28
I am also experiencing the same problem as described above (guake appearing in the middle of the screen), so I'm wondering are there an update on this issue? Thanks heaps!

My `guake --support` output:
```sh
<details><summary>$ guake --support</summary>

Guake Version:		3.7.0

Vte Version:		0.62.1

Vte Runtime Version:	0.62.1

--------------------------------------------------
GTK+ Version:		3.24.24

GDK Backend:		__gi__.GdkWaylandDisplay

--------------------------------------------------
Desktop Session: gnome

--------------------------------------------------
Display: wayland-0

RGBA visual: True

Composited: True

* Monitor: 0 - SHP 0x14d1
    * Geometry:		1920 x 1200 at 0, 0
    * Size:		340 x 210 mm²
    * Primary:		False
    * Refresh rate:	59.95 Hz
    * Subpixel layout:	unknown
```

**Comment by gillescoolen** [comment] 2021-03-08 17:45
I'm having the same issue running Gnome with Wayland.

Guake support output:
```
Guake Version:		3.7.0

Vte Version:		0.62.3

Vte Runtime Version:	0.62.3

--------------------------------------------------
GTK+ Version:		3.24.26

GDK Backend:		__gi__.GdkWaylandDisplay

--------------------------------------------------
Desktop Session: gnome

--------------------------------------------------
Display: wayland-0

RGBA visual: True

Composited: True

* Monitor: 0 - SAM C49RG9x
    * Geometry:		5120 x 1440 at 0, 0
    * Size:		1190 x 340 mm²
    * Primary:		False
    * Refresh rate:	119.97 Hz
    * Subpixel layout:	unknown
```

**Comment by mich2k** [comment] 2021-04-30 21:17
Still having this issue
on xps15 -7590 with Arch, Gnome 3.40 + Wayland
So far, i m using Yakuake that works perfectly



[mich@mich-xps157590 ~]$ guake --support
<details><summary>$ guake --support</summary>

Guake Version:          3.7.0

Vte Version:            0.64.1

Vte Runtime Version:    0.64.1

--------------------------------------------------
GTK+ Version:           3.24.29

GDK Backend:            __gi__.GdkWaylandDisplay

--------------------------------------------------
Desktop Session: gnome

--------------------------------------------------
Display: wayland-0

RGBA visual: True

Composited: True

* Monitor: 0 - SDC 0xa029
    * Geometry:         3840 x 2160 % 2 at 0, 0
    * Size:             340 x 190 mm²
    * Primary:          False
    * Refresh rate:     60.00 Hz
    * Subpixel layout:  unknown

**Comment by AlexAtkinson** [comment] 2021-11-17 02:58
Same issue.

"A problem happened when binding F12 key.
Please use Guake Preferences dialog to choose another key"
Or any other key...

Guake Terminal: 3.7.0
VTE: 0.66.1
VTE runtime: 0.66.1
Gtk: 3.24.30

cat /etc/fedora-release 
Fedora release 35 (Thirty Five)

kf5-config --version
Qt: 5.15.2
KDE Frameworks: 5.87.0
kf5-config: 1.0

**Comment by Davidy22** [comment] 2021-11-17 03:10
That's a different issue @AlexAtkinson, to do with wayland's blocking programs from getting key events when the program isn't in focus. On wayland based desktops you'll need to go to system wide keybindings and bind the key to `guake-toggle`

**Comment by tuopen** [comment] 2022-01-04 11:58
At least on Debian 11 with GNOME the following works as a workaround to force Guake to start it with X11 backend.

In a nutshell run the application with GDK_BACKEND=x11 environment variable. I do this by copying the .desktop file and editing it:

`cd .local/share/applications `
`cp /usr/share/applications/guake.desktop .`

Then edit the following line in the file:

`Exec=guake`
to
`Exec=sh -c "GDK_BACKEND=x11 guake"`

**Comment by Hadatko** [comment] 2022-03-24 05:48
Not an issue for me after installing newer guake using ppa
Guake Terminal: 3.8.1

**Comment by Davidy22** [comment] 2022-06-19 02:47
Closing due to recent window sizing fixes and report of resolution.

**Closed by Davidy22** 2022-06-19 02:47 UTC
Labels: Env: Wayland, GDK: Wayland
