### ISSUE TITLE
super + key doesn't work as intended for toggling visibility

### ISSUE THREAD

**Issue by kurokirasama** [Guake/guake#1890] opened 2021-09-10 16:21 UTC
Be sure to check the existing issues (both open and closed!), and make sure you are running the latest version of Guake.

For how to run the latest Guake in your computer, please refer to [Install from source](https://guake.readthedocs.io/en/latest/user/installing.html#install-from-source).

**Describe the bug**

super + letter key (like super + T) as shortcut for toggling visibility  requires trying 2 times. And if I'm in a text editor, it actually write the letter the first time...

**Expected behavior**

It should work like any other key combination, opening guake right away

**Actual behavior**

Open guake on second try of the key shortcut

**To Reproduce**

change toggle visibility key shortcut to super + T

-------------------------------------------------------------------------------

Please run `$ guake --support`, and paste the results here. Don't put backticks (`` ` ``) around it! The output already contains Markdown formatting. And make sure you run the command **OUTSIDE** the Guake.

<details><summary>$ guake --support</summary>

Guake Version:		3.6.3

Vte Version:		0.60.3

Vte Runtime Version:	0.60.3

--------------------------------------------------
GTK+ Version:		3.24.20

GDK Backend:		GdkX11.X11Display

--------------------------------------------------
Desktop Session: ubuntu

--------------------------------------------------
Display: :0

RGBA visual: True

Composited: True

* Monitor: 0 - BOE eDP-1-1
    * Geometry:		1920 x 1080 at 0, 0
    * Size:		344 x 194 mm²
    * Primary:		True
    * Refresh rate:	60.00 Hz
    * Subpixel layout:	unknown

**Comment by Davidy22** [comment] 2021-09-14 05:05
Just noticed #1076 which is is a duplicate of, closing. More information can be added if there is anything to contribute.

**Closed by Davidy22** 2021-09-14 05:05 UTC
Labels: Type: Defect
