### ISSUE TITLE
Can't hide the window when it's not fullscreen

### ISSUE THREAD

**Issue by elkebirmed** [Guake/guake#647] opened 2015-10-24 16:59 UTC

**Comment by pypingou** [comment] 2015-10-24 17:41
You'll need to give more information than this :)

**Comment by pypingou** [comment] 2015-10-25 14:56
or not :)

**Comment by elkebirmed** [comment] 2015-10-25 15:16
Clicking `F12` bring the terminal window, and `F11` make it bigger (full screes).
when the window is not bigger and i want to close it with `F12` it wont.
but when it's full screen (bigger) it wil be clossed.

I have Ubuntu 15.04

thank you @pypingou :smile:

**Comment by Stibbons** [comment] 2015-10-25 19:27
you means it does not hide when fullscreen?

**Comment by elkebirmed** [comment] 2015-10-26 05:50
@Stibbons yup

**Comment by elkebirmed** [comment] 2015-10-26 05:52
The same issue #648

**Comment by pypingou** [comment] 2015-10-26 08:41
Then let's close this as a duplicate of #648 and keep the discussion there.

**Closed by pypingou** 2015-10-26 08:41 UTC

**Comment by elkebirmed** [comment] 2015-10-26 09:13
OK :+1:
