### ISSUE TITLE
Unreadable text due to incorrect colors

### ISSUE THREAD

**Issue by vbachvarov** [Guake/guake#2000] opened 2022-01-07 22:13 UTC
My Guake terminal displays incorrect colors. The contrast is insufficient with all available themes.
For example, the colored output of `ls` displays directories as dark blue on a black background. The colors are readable in Yakuake but Guake shows them much darker and the text is unreadable.
All my other settings are the same, shell, environment, console settings.

I tried specifying custom colors and copied the colors from Yakuake, however the actually displayed colors in Guake were incorrect (verified with a color picker). For example, chosing the value "#54ff54" for color nr. 2 (dark green) results in actually displayed value "#18b118".

My system is **Linux 5.15.11-gentoo** with **plasma-5.88.0**, **gtk+-2.24.33** and **gtk+-3.24.29**.

TERM settings:
- TERM=xterm-256color
- COLORTERM=yes

Guake support information (omitting the Monitor section):
<details><summary>$ guake --support</summary>

Guake Version:		3.8.0

Vte Version:		0.64.2

Vte Runtime Version:	0.64.2

--------------------------------------------------
GTK+ Version:		3.24.29

GDK Backend:		<GdkX11.X11Display

--------------------------------------------------
Desktop Session: /usr/share/xsessions/plasma

--------------------------------------------------
Display: :0

RGBA visual: True

Composited: True

![изображение](https://user-images.githubusercontent.com/10648575/148614488-50e85114-669e-4b57-88d7-2c613bd3b03c.png)

![изображение](https://user-images.githubusercontent.com/10648575/148614507-170bb630-9f10-4666-a760-a8b8fcb8e065.png)

**Comment by Davidy22** [comment] 2022-01-09 04:16
Unable to observe this for myself. Out of curiosity, how does the following set of commands render for you?

```
echo "\x1b[48;2;0;255;0mHello"
echo "\x1b[48;2;255;0;0mHello"
echo "\x1b[48;2;0;0;255mHello"
echo "\x1b[48;2;255;255;0mHello"
echo "\x1b[48;2;0;255;255mHello"
echo "\x1b[48;2;255;0;255mHello"
echo "\x1b[48;2;255;255;255mHello"
echo "\x1b[48;2;0;0;0mHello"
```

**Comment by vbachvarov** [comment] 2022-01-12 08:41
I have a black background. Line 1 and line 8 - the text is not visible:
![изображение](https://user-images.githubusercontent.com/10648575/149091116-c7e41671-2d3a-4f3e-82c6-77ffaa8d2644.png)

What is especially hard to read is dark blue text on black background:
![изображение](https://user-images.githubusercontent.com/10648575/149093095-f22bbaca-f6f3-44b9-aa00-a3dab361f43c.png)

**Comment by Davidy22** [comment] 2022-01-12 09:37
The thing I put out was RGB color escapes, you can see the color of each line between the 48 and the 0m. Line 1 is expected,  that should be an empty line, line 8 should also be right because that's white on a white background. Looks like true color is rendering fine, went inspecting theme items manually in my settings and from visual inspection it seems like the colors are coming out correctly as per the theme:

![Screenshot from 2022-01-12 17-28-56](https://user-images.githubusercontent.com/872968/149105438-313ee81d-b3e5-44dd-89ce-5e930e168f1b.png)
![d](https://user-images.githubusercontent.com/872968/149105507-a1be2f2c-b7bb-4dfe-ad6c-5b037a5a2b55.png)

Looking at your settings and output, it looks like yours is correct to your theme settings too, but you might have been expecting to see the color from the bottom row instead of the top. On non-bolded text, the full stroke of each character won't necessarily be the exact color from the theme, but on the thickest and brightest parts of characters where they take up the full pixel and in bold glyphs I can confirm with a color picker that the color is correct.

**Comment by vbachvarov** [comment] 2022-01-12 11:53
I understand. I did some more experimenting. It turns out that "ls" renders directories with blue (from the upper row of colors, which is the darker one in my settings):
![изображение](https://user-images.githubusercontent.com/10648575/149135094-6f3249f0-7c93-4f6f-8ca6-07851b919a05.png)

And coincidentally Midnight Commander uses the same value as background.
However, in Yakuake the two colors are different (ls uses lighter color and MC uses a darker blue background). I don't understand how is this possible?
Can it be that Guake renders a subset of all console colors and this causes the two colors above to be mapped to a single value in Guake? I guess my problem comes about from using a 256-color terminal, which maps to only 16 colors in the palette, right? Basically the mapping of the 256 colors to which color from the 16-color palette is used determines what actual color is shown, if I understand correctly.

**Comment by Davidy22** [comment] 2022-01-13 11:06
ANSI 256-color has 256 colors that will be constant across all terminals, and 16 separate codes for theme colors which you're controlling in Guake preferences. Not sure what yakuake does for its preferences, do yakuake themes have more than 16 colors somehow? Are you able to control both colors in yakuake?

Midnight commander does have a settings system to change which theme color it'll use for specific elements, but I would be surprised if theme settings were being loaded differently between yakuake and guake

**Comment by vbachvarov** [comment] 2022-01-14 17:26
I believe Yakuake embeds a Konsole window, because the Konsole settings look identical.
It seems Konsole offers 30 different colors for mapping:
![изображение](https://user-images.githubusercontent.com/10648575/149557998-a17b3c85-316f-4ea3-a21c-0f6d7fc629a3.png)
The red arrow points to the color used as MC background and the blue arrow points to the color used as "ls" directory color. I have no idea how Konsole does that.

In Guake the color 5 from the upper row (dark blue) is used for both outputs. What is the reason that both colors land in the same slot in Guake?

**Comment by Davidy22** [comment] 2022-01-15 02:07
I'd wager probably because our themes just have color and faint color, so programs that use intense/normal color are both using normal color. If we can get the color codes yakuake is I might be able to figure out extending our theming, a lot of existing themes may need to be adjusted

**Comment by Davidy22** [comment] 2022-01-15 04:03
Went and printed the ANSI output for ls to a file, so I'm looking at `\x1b[01;34mguake\x1b[0m` which is the bold text sequence applied to color 4. The sequence `\x1b[94mguake\x1b[0m` is the one that renders bright text, which will give you a bottom row color in Guake. The sequence that mc must be generating background color with according to your theme information is `\x1b[44m`. Bold text being automatically also rendered with the set bright color is a holdover from the ancient days when people's computers didn't have a second font to render bold text in, and worked around it by rendering text as bright. This is deprecated in the main standard now that we have seperate ways to specify boldness and brightness in terminal escapes, and Guake follows this. This issue is happening because the background color in midnight commander is the same color as the color for directories in ls, and on a modern compliant terminal making the text bold in ls won't automatically also change the color. By default, this setup should be difficult to read anyways because light blue on a darker shade of blue or whatever color it is you have set for color 5 isn't terribly easy to read. In the case of your theme the standard and bright colors for color 5 are completely different, which makes your mc theme and ls work together on konsole where bold still completely changes the theme color used. If the default mc background color is color 5, this is a midnight commander issue for choosing a default base background color that's the same as a text output color in ls. If you've been theming mc, you may want to pick a different background color or just use the default terminal background color.

Given the escapes I'm looking at, "fixing" this bug means deviating from current standard and making bolding text change the color used, which is incorrect in other applications, so this will need to be fixed by not using the same base color for background and text in mc.

**Closed by Davidy22** 2022-01-15 04:03 UTC

**Comment by vbachvarov** [comment] 2022-01-15 21:38
Thank you for your explanation. I now better understand the cause.
If I understood correctly, the problem is actually with "ls", which relies on terminals rendering the color as bright, but actually requests bold text.
The solution would be to tweak the 'ls' colors accordingly, correct?

**Comment by Davidy22** [comment] 2022-01-15 23:42
Eh, in most scenarios ls doesn't rely on bold changing font color because terminal backgrounds are usually black, it's really more on mc for choosing a base background color that's the same as a font color in a common utility.
