### ISSUE TITLE
Tab name resets to default

### ISSUE THREAD

**Issue by qualitat1ve** [Guake/guake#1017] opened 2017-10-17 11:36 UTC
Steps to reproduce: 
1) open guake terminal
2) rename tab: guake -r "new tab"
3) RMC -> Preferences
4) close prefs
5) open guake terminal
    Expected result: tab name is "new tab"
    Actual result: tab name was reset to default
6) RMC -> open new tab
    Expected result: 1st tab's name is default
    Actual result: 1st tab's name was set to "new tab"

**Comment by tomersa** [comment] 2017-10-26 17:51
Can't reproduce this.

**Comment by zlatin** [comment] 2017-10-28 16:07
@qualitat1ve what is your guake version?

**Comment by qualitat1ve** [comment] 2017-10-30 10:29
$ guake --version
Guake Terminal 0.8.10

**Comment by tomersa** [comment] 2017-10-31 07:39
Mine is older. That's probably why it doesn't reproduce.

**Comment by mcswizzle** [comment] 2017-11-05 18:07
I just tested this on guake-0.8.8-2.fc26.noarch and got the same behavior. This is frustrating when trying to keep things organized so I agree with the high priority. I was able to reproduce this by doing the following

1. Edit a tab name to be called "123"
2. Right Mouse Click (RMC) and choose Preferences 
3. Close Preferences
4. Tab name is now the determined by what Guake has coded as default for that ssh session/shell

Note: Checking/Unchecking  "Abbreviate directiores in tab names" does not matter.

**Comment by tomersa** [comment] 2017-11-08 12:05
I updated guake. 

For me it doesn't reproduce on:
guake_0.8.8-1_amd64.deb

lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 17.10
Release:	17.10
Codename:	artful

uname -a
Linux tomer-Inspiron-3420 4.13.0-16-generic #19-Ubuntu SMP Wed Oct 11 18:35:14 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by mcswizzle** [comment] 2017-11-09 00:45
Must be the repo lagging then, thanks!

**Comment by aichingm** [comment] 2017-11-22 10:21
I testing it with version 0.8.11.

# Tests
options **Use VTE titles for tab names** and **Abbreviate directories in tab names** are disabled

Test 0
1. Open guake 
1. Run `guake -r "new tab"`
1. RMC -> Prefs
1. 1. Leave  **Use VTE titles for tab names** and **Abbreviate directories in tab names** untouched
1. Close
1. Tab name is still "new_name"
1. Run `echo -en "\033]0;New terminal title\a"`
1. Tab name is still "new_name"

Test 1
1. Open guake 
1. Run `guake -r "new tab"`
1. RMC -> Prefs
1.  turn on **Use VTE titles for tab names** and off again
1. Close
1. Tab name is still "new_name"
1. Run `echo -en "\033]0;New terminal title\a"`
1. Tab name is still "new_name"

Test 2
1. Open guake 
1. Run `guake -r "new tab"`
1. RMC -> Prefs
1.  turn on **Use VTE titles for tab names**
1. Close
1. Tab name is still "new_name"
1. Run `echo -en "\033]0;New terminal title\a"`
1. Tab name is still "new_name"

Test 3
1. Open guake 
1. Run `guake -r "new tab"`
1. RMC -> Prefs
1.  turn on **Use VTE titles for tab names**
1.  turn on **Abbreviate directories in tab names**
1. 1. optional turn off **Abbreviate directories in tab names**
1. Show guake (even without closing the prefs panel)
1. Tab name changed to "Terminal"
1. Run `echo -en "\033]0;New terminal title\a"`
1. Tab name is still "Terminal"


# Conclusion

I think tests 0 to 2 work as intended and documented.

From what I can tell about test 3, **Use VTE titles for tab names** respects user set names but **Abbreviate directories in tab names** does not (only at the moment of turning it on). **Abbreviate directories in tab names** should not touch names for terminals which have been set by the user. This is a bug.

**Comment by Fuxy22** [comment] 2018-01-23 02:19
I'm actually getting this on guake 3.0.3 now.

The only thing different I noticed is when I create a new tab after going to preferences the names of the tabs show up again.

**Comment by mart-r** [comment] 2018-08-15 09:08
@Fuxy22 
Thank you! Had the exact same problem and your description saves me from having to retype them all the damn time.

Still an annoying bug, however.
`guake --version
Guake Terminal: 3.3.2
VTE: 0.52.2
VTE runtime: 0.52.2
Gtk: 3.22.30`

**Closed** 2018-09-21 17:58 UTC
Labels: Priority: High, Type: Defect
