### ISSUE TITLE
"prefix" no longer considered

### ISSUE THREAD

**Issue by tarnh** [Guake/guake#1683] opened 2019-11-14 08:21 UTC
With current git master `make prefix=/usr install` no longer has an effect.

Output is always at /usr/local which is unwanted by me and my distro.

**Comment by MorganAntonsson** [comment] 2020-02-17 13:48
Use PREFIX instead, e.g.

make PREFIX=/usr install

**Comment by Davidy22** [comment] 2021-09-04 16:30
Closing because solution is given and not a bug

**Closed by Davidy22** 2021-09-04 16:30 UTC
Labels: Resolution: Invalid
