### ISSUE TITLE
-execute-command fails

### ISSUE THREAD

**Issue by dga4130-renato** [Guake/guake#2064] opened 2022-03-31 20:47 UTC
Ubuntu 22.04
guake 3.8.5-1

unable to open a tab with -e COMMAND, --execute-command=COMMAND

tab opens but without running the program inside.

**Comment by Davidy22** [comment] 2022-04-01 14:45
Closing because duplicate of #2042, a fix has been outlined and put forward there, now just needs review

**Closed** 2022-04-01 14:45 UTC
