### ISSUE TITLE
Guake disappears if you select "Show Desktop"

### ISSUE THREAD

**Issue by kikecalpe** [Guake/guake#45] opened 2013-04-14 16:04 UTC
Guake disappears if you select "Show Desktop" http://guake.org/ticket/506
Reported by:    dsaracini   Owned by:   somebody
Priority:   minor   Milestone:  0.5.0
Component:  guake   Version:    1.0
Keywords:       Cc:  
Description

In Ubuntu 12.04, if you press "Alt + Tab" to move between applications and you select "Show Desktop" while Guake is displayed, then Guake is hiddened and cannot be show again. If you grep the processes (ps -A|grep 'guake') you will not find it. The only solution that I have found to get Guake back is to reboot. :((

**Comment by mfrasca** [comment] 2015-03-20 19:15
it's still there on 0.4.4-1ubuntu1 (the one coming with ubuntu 14.04 LTS).
@mbondfusion 's workaround works fine, thanks.

**Comment by EightArmCode** [comment] 2016-01-29 14:45
This fix did not work for me.

**Comment by mfrasca** [comment] 2016-01-29 15:36
this works for me, not to avoid the problem but to fix it:
```bash
#!/bin/bash
PARENT=$(xwininfo -name "Guake!" -int -tree | sed -ne '/Root/s/[^0-9]//gp')
xdotool search --name "Guake!" windowreparent $PARENT
```
only trouble, I must remember I have, and I hope that naming it like `guake-reparent` will help me find it when I need it.

**Comment by peter-umb** [comment] 2016-05-27 13:05
I can confirm this is still a bug in ubuntu 16.04. alt-tabbing to the hide desktop icon did not bring it back. Is there any way to add an option to allow the icon to show in alt-tab?

**Comment by mfrasca** [comment] 2016-06-03 09:53
> this is still a bug in ubuntu 16.04
ubuntu 16.04.0 contains guake 0.8.4

**Comment by Saulzar** [comment] 2016-07-13 08:50
Priority: Low? Is that some cruel joke?

This bug has been extremely annoying, almost to the point where guake is totally unusable and has cost me a lot of time re-opening terminals.

**Comment by Stibbons** [comment] 2016-07-13 08:57
Yes I know but this is a bug in GTK2. Won't be fixed until port to GTK3 (which I hope to finish during summer)

**Comment by vjrj** [comment] 2016-07-22 08:09
If helps, the workaround in this https://github.com/Guake/guake/issues/540#issuecomment-151403225 works for me. I'm using ubuntu 16.04 + yakuake that suffer the same bug.

**Comment by daniel-dong** [comment] 2016-07-23 08:32
```
PARENT=$(xwininfo -name "Guake！" -int -tree | sed -ne '/Root/s/[^0-9]//gp')
xdotool search --name "Guake！" windowreparent $PARENT
```
This works on Ubuntu 16.04 (Guake 0.8.4). Note it's "Guake！" (full-width exclamation mark) not "Guake!".

**Comment by Saulzar** [comment] 2016-07-23 09:07
Yes script is a lifesaver! Thanks!

The priority makes more sense in light of the reason.

**Comment by mclemme** [comment] 2016-10-23 18:57
Thanks for the windowreparent script, works like a charm on Ubuntu 14.04 and guake **0.4.4-1ubuntu1**.

If you don't use the "Show Desktop" option in the alt-tab switcher you can disable it to avoid the issue altogether. Install compizconfig-settings-manager:

`sudo apt-get install compizconfig-settings-manager`

Launch it from the menu, go to **Ubuntu Unity Plugin** -> **Switcher tab** -> Check **Disable Show Desktop in the Switcher**.

**Comment by alainwolf** [comment] 2017-11-27 01:04
Tip: If you use [quake-indicator](http://guake-indicator.ozzyboshi.com/) add the those two lines to the Menu.

**Comment by aichingm** [comment] 2018-09-21 13:11
This seams to be fixed in the GTK3 version.  

Closing this issue since 8.x.x is not supported anymore.

**Closed by aichingm** 2018-09-21 13:11 UTC
Labels: Priority: Low, Type: Defect
