### ISSUE TITLE
Preferences panel is invisible

### ISSUE THREAD

**Issue by GijsGoudzwaard** [Guake/guake#1182] opened 2018-01-31 20:48 UTC
Version 3.0.5.
Elementary OS Loki 0.4

**Comment by GijsGoudzwaard** [comment] 2018-02-01 12:18
When using expose windows it does show that the preferences panel is there, just not visible.

**Comment by Davidy22** [comment] 2021-09-30 14:34
Does this still occur for you in latest git master? If you can't compile, we'll soon have a release out via pypi as well.

**Comment by Davidy22** [comment] 2021-09-30 20:22
Since this report is for older versions and there's no chance of reproducing anymore, closing.

**Closed by Davidy22** 2021-09-30 20:22 UTC
Labels: Type: Need More Info
