### ISSUE TITLE
Tabs width

### ISSUE THREAD

**Issue by ka4eli** [Guake/guake#981] opened 2017-07-25 21:20 UTC
Maybe it's a wrong place to share user's opinion but I like this project very much and want to use it in future. Now I have to downgrade my guake version to 0.8.8 because of new feature - tabs width now takes whole free space. It's very inconvenient for me but I like to receive future updates. Is it possible to add ability to disable this feature? Maybe there are also people who need it, not only me)). In any case thank you for your work! 

OFFTOPIC:
Do you plan to implement current tab highlighting?

**Comment by whyouwannakillme** [comment] 2017-08-06 09:33
I join the aforesaid, thx.

**Comment by Santinell** [comment] 2017-08-08 06:51
I agree, tabs are too big. 
Looks very ugly.
It will be nice if you could return old behaviour, or make it optional

**Comment by aichingm** [comment] 2017-08-08 09:42
For everyone who is interested in working on this issue have a look at 08c1b84624fda08f9bea665436fc2f6b10c8caf4 and 
c27ea6ab5fd178d0ba59237c426c4e73e55b6b25

**Comment by SparkyBluefang** [comment] 2017-08-08 19:04
This is a duplicate of #962

**Comment by Davidy22** [comment] 2022-04-20 04:48
Resolved in #989

**Closed by Davidy22** 2022-04-20 04:48 UTC
