### ISSUE TITLE
Guake not work nicely with gnome3 

### ISSUE THREAD

**Issue by sandikata** [Guake/guake#1829] opened 2021-02-02 15:07 UTC
**Describe the bug**
guake is staying always on top even if this option is disabled.

**Expected behavior**
guake shouldn't stay on top of another apps which are on focus at the time.

**Actual behavior**
staying on top over on focus apps

Provide the steps to reproduce the behavior

   guake --support               
<details><summary>$ guake --support</summary>

Guake Version:		3.7.0

Vte Version:		0.62.2

Vte Runtime Version:	0.62.2

--------------------------------------------------
GTK+ Version:		3.24.24

GDK Backend:		GdkX11.X11Display

--------------------------------------------------
Desktop Session: gnome-xorg

--------------------------------------------------
Display: :0

RGBA visual: True

Composited: True

* Monitor: 0 - PHL DisplayPort-2
    * Geometry:		2560 x 1440 at 0, 0
    * Size:		527 x 296 mm²
    * Primary:		True
    * Refresh rate:	74.97 Hz
    * Subpixel layout:	unknown

-------------------------------------------------------------------------------

Please run `$ guake --support`, and paste the results here. Don't put backticks (`` ` ``) around it! The output already contains Markdown formatting. And make sure you run the command **OUTSIDE** the Guake.

**Comment by Davidy22** [comment] 2021-09-05 00:27
Closing because of duplicate of #1731, if you have more information you can provide it there.

**Closed by Davidy22** 2021-09-05 00:27 UTC
