### ISSUE TITLE
feature request : search in current terminal

### ISSUE THREAD

**Issue by FredMour** [Guake/guake#627] opened 2015-10-01 14:46 UTC
Dear Guake,

I am looking a feature to do a "grep" in the terminal log.

Currently I do "click right" / "record"  a destination file name
and a grep in this file.

Could it be possible to have a shortcup for this kind of feature ? 
or the possibility to have an alias grep_quake_in_shell to search a string ? 

Does it already exist ?

Best Regards,
Frédéric

**Comment by thardev** [comment] 2015-10-21 16:56
Hello @FredMour tell me if I'm wrong, but are you looking for the same feature as when you do Ctrl+Shift+F in gnome-terminal?

**Comment by FredMour** [comment] 2015-10-21 17:52
Dear Dante, 

Yes Sir. 
Is there a similair possibility with guake ? 

Regards, 
Frédérc 


----- Original Message -----

**Comment by Ozzyboshi** [comment] 2015-10-21 19:51
i'd like it

**Comment by Stibbons** [comment] 2015-10-22 10:57
This requires to rewrite everything in gtk3 to use latest version of the python-vte. I am on it, but not so much time to do it until the end of this year :(

**Comment by Stibbons** [comment] 2018-01-11 13:29
Really hope to be able to do it soon!

**Comment by Stibbons** [comment] 2018-01-11 13:29
duplicate of #116

**Closed by Stibbons** 2018-01-11 13:29 UTC
Labels: Priority:Low, Type: Defect
