### ISSUE TITLE
A closed subterminal returns back after restarting Guake

### ISSUE THREAD

**Issue by ildar130** [Guake/guake#1686] opened 2019-11-30 18:03 UTC
When a terminal is splitted and then one of the subterminals is closed, it returns back after restarting Guake.
So it is virtually impossible to close a subterminal forever).
It only helps to close the tab.

**Comment by Polar-Fox** [comment] 2019-12-15 18:37
UPD:
Guake.save_tabs() function is not invoked on closing a subterminal.

The bug happens only when the "Automatically save session when the tabs has been modified" checkbox is on and Close terminal was the last action. If the user clicks "Save tabs" or opens/closes another tab, the tabs state is saved.

**Comment by Davidy22** [comment] 2021-09-05 02:06
Unable to reproduce. Are you still encountering this issue?

**Comment by Davidy22** [comment] 2021-11-01 12:58
Actually, think I'm able to reproduce, can look into a fix.

**Closed** 2022-04-28 08:45 UTC
Labels: Type: Defect
