### ISSUE TITLE
Tighter integration with gnome-shell

### ISSUE THREAD

**Issue by viccuad** [Guake/guake#304] opened 2014-03-26 00:59 UTC
I have come by this gnome-shell extension: [https://github.com/zzrough/gs-extensions-drop-down-terminal](https://github.com/zzrough/gs-extensions-drop-down-terminal) which provides a quake-like terminal also, and the animation is pretty smooth.

Is it possible to implement something like this in guake?

thanks in advance

**Comment by kwill** [comment] 2017-05-25 13:32
Duplicate of https://github.com/Guake/guake/issues/701 ?

**Comment by Stibbons** [comment] 2018-01-11 12:30
If you want this feature, please vote on [FeatHub](https://feathub.com/Guake/guake)

**Closed by Stibbons** 2018-01-11 12:30 UTC
Labels: Priority:Low, Type: Feature Request
