### ISSUE TITLE
Ubuntu Hirsute keyboard shortcut error

### ISSUE THREAD

**Issue by chosroes** [Guake/guake#1852] opened 2021-05-17 08:34 UTC
**Describe the bug**

In Ubuntu 20.10 F12 was my shortcut for toggling visibility, in hirsute, the shortcut is still F12, but not working, and when I try to use anything, guake say there is a problem. And i don't have anymore  the icon saying guake is running in background.

**Expected behavior**

Shortcut and shortcut edition without error.

**Actual behavior**

Toggle display shortcut working

**To Reproduce**

Update from Ubuntu 20.10 to 21.04 and verify if shortcut works.

-------------------------------------------------------------------------------

Guake Version:		3.6.3

Vte Version:		0.62.3

Vte Runtime Version:	0.62.3

--------------------------------------------------
GTK+ Version:		3.24.25

GDK Backend:		__gi__.GdkWaylandDisplay

--------------------------------------------------
Desktop Session: ubuntu

--------------------------------------------------
Display: wayland-0

RGBA visual: True

Composited: True

* Monitor: 0 - VSC XG2700 SERIES
    * Geometry:		3840 x 2160 at 0, 0
    * Size:		600 x 340 mm²
    * Primary:		False
    * Refresh rate:	30.00 Hz
    * Subpixel layout:	unknown
* Monitor: 1 - AUO 0x5b2d
    * Geometry:		1920 x 1080 at 3840, 569
    * Size:		290 x 160 mm²
    * Primary:		False
    * Refresh rate:	60.03 Hz
    * Subpixel layout:	unknown

**Comment by chosroes** [comment] 2021-05-21 06:42
It seems OK when switching back to X instead of wayland

**Comment by MinDBreaK** [comment] 2021-06-24 09:11
I can add that any binding will actually fail with wayland.

**Comment by Davidy22** [comment] 2021-09-04 15:45
Duplicate of an unfortunately long-lived bug #492

**Closed by Davidy22** 2021-09-04 15:45 UTC
