### ISSUE TITLE
Search feature not working as expected

### ISSUE THREAD

**Issue by tomchor** [Guake/guake#1824] opened 2021-01-04 19:24 UTC
I noticed that I can't search for words in Guake. I'm not sure if I'm missing something and misinterpreting the command, but I expected that when issuing `crtl + shift + F` Guake would search from matches of whatever I type, but that's not happening.

For example, in the example below I would expect the word `Dropbox` in the terminal (bottom left of the figure) to be highlighted after I typed `Dropbox` in the search box (bottom right of the figure) and pressed enter. 

![Screenshot from 2021-01-04 11-17-21](https://user-images.githubusercontent.com/13205162/103570972-ec2ab600-4e7e-11eb-957d-d77d951be642.png)

However, after pressing enter, clicking on the up and down arrows, etc, nothing happens. 
Am I missing something?

By the way I'm using Arch Linux and I've installed guake from the AUR via `yay`.

-------------------------------------------------------------------------------

<details><summary>$ guake --support</summary>

Guake Version:		3.7.0

Vte Version:		0.62.1

Vte Runtime Version:	0.62.1

--------------------------------------------------
GTK+ Version:		3.24.24

GDK Backend:		GdkX11.X11Display

--------------------------------------------------
Desktop Session: Cinnamon

--------------------------------------------------
Display: :0

RGBA visual: True

Composited: True

* Monitor: 0 - BOE eDP-1
    * Geometry:		1920 x 1080 at 0, 0
    * Size:		294 x 165 mm²
    * Primary:		True
    * Refresh rate:	59.98 Hz
    * Subpixel layout:	unknown

**Comment by ivoshm** [comment] 2021-01-05 11:43
Duplicate of #1752 ...

**Comment by Davidy22** [comment] 2021-09-04 13:22
Closing because duplicate, but this is a bug I'm hoping to get cleared off with the merge of an aging pull request

**Closed by Davidy22** 2021-09-04 13:22 UTC

**Comment by dpinol** [comment] 2022-02-10 08:06
For the record, the fix is not available in Ubuntu 21.10 by default.
You can get it with this repo `sudo add-apt-repository ppa:linuxuprising/guake`

**Comment by duven87** [comment] 2023-10-13 10:31
linuxuprising-guake-jammy.list
Hi have a problem with the search box too.
the first time (ctrl+shift +S) appears, the second time not, but works because I type and I can see that are searching what Im typing..
Im using Linux Mint 21.2 with repo linuxuprising-guake-jammy.list
