### ISSUE TITLE
Mouse is not working properly in Guake with Midnight Commander

### ISSUE THREAD

**Issue by igorog** [Guake/guake#1244] opened 2018-04-10 04:30 UTC
Arch Linux '**any**' Repository: **guake 3.0.5-2** Community Maintainers: Balló György Build Date: 2018-03-27 16:51 UTC Last Updated: 2018-03-27 17:00 UTC
System: (Linux 4.15.15-1-ARCH #1 SMP PREEMPT Sat Mar 31 23:59:25 UTC 2018 **x86_64** GNU/Linux)
**DE:** Cinnamon
**Midnight Commander** v.4.8.20
**Steps to reproduce:**  Clicking the right mouse button on the files in the MC-panel does not mark the files, but simply a context menu Guake. At the same time, everything works correctly in gnome-terminal - files and folders are marked with the right button.

Output when mouse right click in MC-panel:
```
found tag: -1, item: None
Current link under cursor: None
found tag: -1, item: None
Current link under cursor: None
found tag: -1, item: None
Current link under cursor: None`
```

**Comment by egmontkob** [comment] 2018-04-11 19:24
Dupe of #1096.

**Closed** 2018-04-11 20:37 UTC

**Comment by igorog** [comment] 2018-04-12 03:02
Bug 13299 - gnome-terminal ???: Bad Shift + Right Button ???

Sorry, maybe I didn't understand something, but what does that have to do with my problem? Selection of files in the MC-panel is made simply by the right mouse button, WITHOUT simultaneous pressing of the Shift key.
At the same time, everything works perfectly in the gnome-terminal. When I right-click on a file, the file is marked in yellow. This is the expected action and it works correctly. **It DOESN't WORK in Guake v3.0.5.**
At version 0.8.5 everything worked fine.

**Comment by igorog** [comment] 2018-04-17 03:33
Hello! Today I finally put a new version of Guake v3.2, and'm checking again mouse in MC-panel. By default, in MC, when you press the right mouse button on a file or folder - they should stand out and be **selected-marked** (in yellow), to continue with the selected file, it was possible to perform a **GROUP operation**. But the files are not marked! For some reason, in gnome-terminal it works.
Check it out, please!

**Comment by gsemet** [comment] 2018-04-17 08:27
Ok, found the issue

**Comment by gsemet** [comment] 2018-04-17 08:39
For the double click, it seems like it is a timing issue, not intended... so don't know how to deal with it

**Comment by igorog** [comment] 2018-04-18 03:41
Applied the hotfix and .... voila: everything works fine, including double-click and right-click. This is super! Thank you!
