### ISSUE TITLE
Right-click -> Close on tab closes terminal but does not remove tab

### ISSUE THREAD

**Issue by SparkyBluefang** [Guake/guake#1438] opened 2018-10-06 20:15 UTC
Guake Terminal: 3.4.0
VTE: 0.48.4
VTE runtime: 0.48.4
Gtk: 3.22.30

Trying to close a tab via Right-clicking on the tab and selecting `Close` causes the terminal to be destroyed, but the tab is not closed. The scroll bar is now on the left side of guake and the space to the right is white.

When guake is in this state, trying to quit (open a new tab and Right-click -> Quit) throws an exception and guake does not exit.
```
Current link under cursor: None
Current link under cursor: None
Custom file does not exit: /home/sparky/.config/guake/custom_command.json
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/guake/callbacks.py", line 95, in on_quit
    self.notebook.guake.accel_quit()
  File "/usr/lib64/python3.6/site-packages/guake/guake_app.py", line 692, in accel_quit
    procs = self.notebook.get_running_fg_processes_count()
  File "/usr/lib64/python3.6/site-packages/guake/notebook.py", line 98, in get_running_fg_processes_count
    fg_proc_count += self.get_running_fg_processes_count_page(self.page_num(page))
  File "/usr/lib64/python3.6/site-packages/guake/notebook.py", line 104, in get_running_fg_processes_count_page
    fdpty = terminal.get_pty().get_fd()
AttributeError: 'NoneType' object has no attribute 'get_fd'

```

Using `Ctrl`+`d` in a terminal correctly closes the terminal and removes the tab.

**Comment by gsemet** [comment] 2018-10-08 11:27
Seems a duplicate of #1416.

**Comment by vsraptor** [comment] 2018-12-10 21:43
confirm ....

Even typing 'exit' doesn't work. Just prints 'exit' and freezes there ....

**Comment by benguyer** [comment] 2018-12-13 03:07
I can confirm as well on Mint 18.3 Cinnamon. Oddly though, I don't have the same issues with typing 'exit' like @vsraptor does. The only way I can get this bug to appear is by right-clicking on the tab and selecting 'Close'.

Guake Terminal: 3.4.1
VTE: 0.42.5
VTE runtime: 0.42.5
Gtk: 3.18.9

Let me know if there's any other information I can provide to help.

**Comment by aichingm** [comment] 2019-01-04 14:44
@vsraptor That's a different issue and it is fixed already. 

As said in #1416 I can't reproduce this, and the only thing I can add to the problem is that it does not happen with:
Guake Terminal: 3.4.0
VTE: 0.54.3
VTE runtime: 0.54.3
Gtk: 3.24.2

which are quite significant version bumps...

**Comment by SparkyBluefang** [comment] 2019-01-09 23:09
I can confirm that updating VTE from 0.48.4 to 0.54.1 fixes this issue.

I believe VTE 0.48 is the minimum supported version, so this should still be fixed (or the minimum version bumped).

**Closed** 2019-04-03 12:08 UTC
Labels: Priority: URGENT, Type: Defect

**Comment by amezin** [comment] 2019-04-05 10:47
After the fix was merged, right-click+Close closes two tabs, the one that I intended to close, and also a tab after it. Only closing the last tab works correctly (because theres nothing after it)

Arch Linux, guake 3.5.0-1, vte3 0.56.0-1

Reverting the patch restores correct behavior, only one tab closes

**Comment by gsemet** [comment] 2019-04-09 14:03
Yes, can you put this traceback in #1513 please

**Comment by YerongLi** [comment] 2019-11-12 00:18
I am running Guake 3.4.0-1 from the ubuntu(18.0.4) repo and **right click with close tab** won't close the tab that I want to close.
