### ISSUE TITLE
Guake 3.4 doesn't correcly appear on mouse display

### ISSUE THREAD

**Issue by eblis** [Guake/guake#1453] opened 2018-10-24 08:22 UTC
- **Guake 3.4.0**
 - Linux Mint 19 (x64)

I have the option "Appear on mouse display" enabled but the window doesn't always appear on the display where the mouse is.

I have 3 monitors - 1 left, 2 center (primary) and 3 right.
If I enable the Guake window while the mouse is on the 2nd (primary) monitor the window will alternatively appear on monitor 1 and monitor 2 (clicking to show/hide the window multiple times). It will appear once on monitor 1, then on monitor 2, then repeat.

If the mouse is on monitor 3 the window will alternatively appear on monitor 1 and 3.

I've recently updated from Guake 3.3.2 where I didn't have this problem.

**Comment by PavelSmokorovskiy** [comment] 2018-11-10 12:47
I have the same problem on ubuntu gnome 3.3

**Comment by L3vi47h4N** [comment] 2018-11-17 15:00
https://github.com/Guake/guake/issues/1450 seems to be a duplicate of this issue. Might want to try the solution there.

**Comment by eblis** [comment] 2018-11-19 09:29
I've gotten around the issue by forcing the terminal to always show on a particular terminal.

**Comment by PavelSmokorovskiy** [comment] 2018-11-19 09:32
There is a solution https://github.com/Guake/guake/issues/1450

**Closed** 2018-11-20 12:14 UTC

**Comment by eric-saintetienne** [comment] 2021-03-22 21:48
This fix no longer works.

```
$ guake --version
Guake Terminal: 3.6.3
VTE: 0.62.3
VTE runtime: 0.62.3
Gtk: 3.24.27
```

The fix is present in this version:
```
```
$ grep -nB1 -A4 deprecated /usr/lib/python3.9/site-packages/guake/utils.py 
269-
270:            # TODO PORT get_pointer is deprecated
271-            # https://developer.gnome.org/gtk3/stable/GtkWidget.html#gtk-widget-get-pointer
272-            win, x, y, _ = screen.get_root_window().get_pointer()
273-            dest_screen = screen.get_monitor_at_point(x, y)
274-
```

But hitting the "Toggle Guak Visibility" key (F9 in my case) always show the guake window on the same screen, irrespectively of the mouse location.
![image](https://user-images.githubusercontent.com/14312824/112062698-2b040a00-8b58-11eb-8649-2f49e5bc91ab.png)

![image](https://user-images.githubusercontent.com/14312824/112062831-6272b680-8b58-11eb-98b3-7bb26146d58d.png)

**Comment by eric-saintetienne** [comment] 2021-03-22 21:56
Ah! I just found out by running `guake --support` that the second monitor was starting at offset 1919, not 1920.

That's why it was always showing on the same monitor!
