### ISSUE TITLE
Guake 0.8.0 "Toggle Guake Visibilty" shortcut binded to "`" (tilde) is not working on non-Us keyboard layout

### ISSUE THREAD

**Issue by slash686** [Guake/guake#617] opened 2015-09-16 06:37 UTC
"Toggle Guake Visibilty" shortcut binding to "`" (tilde) is not working when using non-Us keyboard layout (Russian). Though it was working in a version supplied through Ubuntu Software Center (I think it was 0.4.x version).
Ubuntu 14.04 Unity
Guake 0.8.0

**Comment by Stibbons** [comment] 2015-09-16 09:05
by default it is F12. Maybe a packaging error

**Comment by thardev** [comment] 2015-10-21 11:23
Hello @slash686 have you tried if it works with the latest version of Guake? I can't reproduce it in 0.8.2

**Comment by slash686** [comment] 2015-10-22 16:18
Hey @thardev , not yet. Going to give it a try soon.

**Comment by slash686** [comment] 2015-10-22 16:25
@thardev, it looks like the latest guake version is 0.8.1. Can't find any signs of 0.8.2

**Comment by Stibbons** [comment] 2015-10-22 17:06
yes it's 0.8.1

**Comment by thardev** [comment] 2015-10-22 17:19
Yes, sorry, my mistake :bowtie: , I'll try to reproduce with the same settings as you, because I was trying with Debian Jessie... so can you explain a bit further the steps you did? :smile:

**Comment by slash686** [comment] 2015-10-23 07:36
@thardev looks like poblem still persists for me with latest guake version.
What I'm trying to do:
Change keyboard shortcut for "Toggling guake visibility" and bind it to tilde/backtick. While I'm on English keyboard layout, pressing backtick key opens guake. All is fine.
Then, change keyboard layout to Russian, press backtick - nothing happens. Switch layout back to english - it works again.
Please note that this was working with guake version 0.4.1 (i believe), I've been able to fire up guake with backtick key when both on English or Russian keyboard layout on old version.

**Comment by Stibbons** [comment] 2015-10-23 11:04
This is certainly due to the new keybinder. Can you check at this project to know if it is a know issue?

**Comment by slash686** [comment] 2015-10-23 17:46
@Stibbons sure, the closest issue that I can find is #226 which is dated back to 2013. Sadly no progress on that one.

**Comment by jenrik** [comment] 2015-11-01 11:04
I can't reproduce the bug with Guake 0.8.3. I bound the "Toggle Guake visibility" button to "`" then tried with both Danish and Russian keyboard layout, and English as a control, and I it work.
I tested it on Arch Linux, and I used xfce's keyboard layout switcher.

**Comment by Davidy22** [comment] 2021-09-16 22:36
Keyboard shortcuts code has been rewritten somewhat, does this still occur for you?

**Comment by Davidy22** [comment] 2022-04-21 11:33
Closing due to no reply, reopen if still relevant.

**Closed by Davidy22** 2022-04-21 11:33 UTC
Labels: Type: Defect, Priority: Low
