### ISSUE TITLE
Guake does not start after Debian Sid upgrade.

### ISSUE THREAD

**Issue by bennybenjaman** [Guake/guake#2111] opened 2022-07-15 15:41 UTC
**Describe the bug**

Guake Does not start after latest upgrade in Debian Sid

**Expected behavior**

Guake would start normally.

**Actual behavior**

After starting guake this output is given

Guake not running, starting it
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 177, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 361, in get_name_owner
    return self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.guake3.RemoteControl': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/guake/main.py", line 473, in main
    remote_object = bus.get_object(DBUS_NAME, DBUS_PATH)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 241, in get_object
    return self.ProxyObjectClass(self, bus_name, object_path,
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 250, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 182, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 277, in start_service_by_name
    return (True, self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.guake3.RemoteControl was not provided by any .service files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/guake", line 10, in <module>
    sys.exit(exec_main())
  File "/usr/lib/python3/dist-packages/guake/main.py", line 648, in exec_main
    if not main():
  File "/usr/lib/python3/dist-packages/guake/main.py", line 487, in main
    from guake.guake_app import Guake
  File "/usr/lib/python3/dist-packages/guake/guake_app.py", line 49, in <module>
    from guake import notifier
  File "/usr/lib/python3/dist-packages/guake/notifier.py", line 23, in <module>
    gi.require_version("Notify", "0.7")
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available for version %s' %
ValueError: Namespace Notify not available for version 0.7

**To Reproduce**
Upgrade Debian Sid 

-------------------------------------------------------------------------------

<details><summary>$ guake --support</summary>

Guake Version:          3.9.0

Vte Version:            0.68.0

Vte Runtime Version:    0.68.0

--------------------------------------------------
GTK+ Version:           3.24.34

GDK Backend:            <GdkX11.X11Display

--------------------------------------------------
Desktop Session: plasma

--------------------------------------------------
Display: :0

RGBA visual: True

Composited: True

* Monitor: 0 - BNQ DP-4
    * Geometry:         1920 x 1080 at 1920, 309
    * Size:             540 x 300 mm²
    * Primary:          True
    * Refresh rate:     143.981 Hz
    * Subpixel layout:  unknown
* Monitor: 1 - DEL DP-0
    * Geometry:         1080 x 1920 at 3840, 0
    * Size:             510 x 287 mm²
    * Primary:          False
    * Refresh rate:     60.0 Hz
    * Subpixel layout:  unknown
* Monitor: 2 - DEL DP-2
    * Geometry:         1920 x 1080 at 0, 598
    * Size:             510 x 287 mm²
    * Primary:          False
    * Refresh rate:     60.0 Hz
    * Subpixel layout:  unknown

**Comment by kornrunner** [comment] 2022-07-15 19:56
I believe this is actually a duplicate of #2110

**Comment by bugtracker2019** [comment] 2022-07-16 09:44
Yes, it is. Just change the value from 0.7 to 0.8 in /usr/lib/python3/dist-packages/guake/notifier.py

**Closed** 2022-07-17 10:02 UTC
