### ISSUE TITLE
Open new tab in current directory doesn't work

### ISSUE THREAD

**Issue by shayanh** [Guake/guake#578] opened 2015-06-28 09:25 UTC
I have Arch Linux. When I check "Open new tab in current directory" it doesn't work and next time I open Guake preferences app "Open new tab in current directory" option become unchecked.

**Comment by Stibbons** [comment] 2015-06-28 16:58
I saw there are some regression in some options in the panel, i'll check them. Thanks for the report

**Comment by Jehan** [comment] 2015-06-28 18:36
Just for info, I have the same issue on the guake 0.7.2 installed in the official repository of my newly installed Fedora 22.

**Comment by mikestephens** [comment] 2015-07-01 21:45
The current working workaround is to add a boolean key "open_tab_cwd" and set it to True in gconf:/apps/guake/general

**Comment by Jehan** [comment] 2015-07-02 11:57
Hi,

I see the file .config/gconf/apps/guake/general/%gconf.xml in which I added:
<entry name="open_tab_cwd" mtime="1435691220" type="bool" value="true"/>
Following the syntax I see in the file. But even after restarting guake, it still does not open tabs in the current directory. Did I misunderstand your workaround?

**Comment by mikestephens** [comment] 2015-07-02 16:12
That is interesting.. Here is mine:

`<entry name="open_tab_cwd" mtime="1435609662" type="bool" value="true"/>`

It looks the same to me unless I am missing something. I doubt it makes a difference but I used [this](https://www.archlinux.org/packages/extra/i686/gconf-editor/) program on my arch install to add `open_tab_cwd`.

**Comment by ShayanH** [comment] 2015-07-02 20:35
Thanks a lot, it works for me.

**Comment by Jehan** [comment] 2015-07-02 21:02
Hi,

On Thu, Jul 2, 2015 at 6:12 PM, Michael Stephens <notifications@github.com>
wrote:

> That is interesting.. Here is mine:
>
> <entry name="open_tab_cwd" mtime="1435609662" type="bool" value="true"/>
>
> It looks the same to me unless I am missing something. I doubt it makes a
> difference but I used this
> <https://www.archlinux.org/packages/extra/i686/gconf-editor/> program on
> my arch install to add open_tab_cwd.
>

I installed gconf-editor, and when I find the key in apps/guake/general,
there is a warning "This key has no schema".
Maybe this variable is called differently in Guake 0.7.2?

Jehan

**Comment by mikestephens** [comment] 2015-07-02 21:21
Hmm that is odd. I just deleted the key and readded it in 0.7.3 and got no such error. I looked through the commits between 0.7.2 and 0.7.3 and I didn't see anything that could cause the issue (to my knowledge). 

@Stibbons would probably know better than me though. Potentially it is different in Fedora than Arch?

**Comment by Stibbons** [comment] 2015-07-02 21:51
no recent changes. Look like an installation issue... execute make install and restart the computer?

**Comment by Jehan** [comment] 2015-07-02 21:56
Hi,

This is a clean install from the Fedora package management system. This is
not a self-built guake.

Jehan

**Comment by pypingou** [comment] 2015-07-03 05:43
You likely have to play with ``/etc/gconf/schemas/guake.schemas`` as well

**Comment by Jehan** [comment] 2015-07-03 09:51
Hi,

Awesome. I added the key in the schema, now it works. :-)
Thanks for the workaround.

Jehan

On Fri, Jul 3, 2015 at 7:43 AM, Pierre-Yves Chibon <notifications@github.com

**Comment by SukkoPera** [comment] 2015-08-11 16:48
I confirm this. It seems that none of the settings of the "Shell" tab are being saved.

(guake 0.7.2 just built from sources)

**Comment by tirkarthi** [comment] 2015-09-26 10:55
`src/guake/prefs.py` contains the function `on_open_tab_cwd_toggled` which seems have not been linked to the checkbox 'open new tab in current directory'. As @SukkoPera points out none of the settings in the shell tab are getting saved which also leads to the issue https://github.com/Guake/guake/issues/619 . The code has been written to pass the appropriate parameter to `fork_command` while initializing the terminal but its not linked to `data/prefs.glade`.

**Comment by kossa** [comment] 2015-10-27 11:39
I had the same problem, using Arch, I fixed it as @mikestephens said :
```
The current working workaround is to add a boolean key open_tab_cwd and set it to True in gconf:/apps/guake/general
```

**Comment by indraforyou** [comment] 2015-12-20 21:02
Reporting the same problem on Ubuntu 15.10 .. currently going with the workaround.

**Comment by lkorba** [comment] 2016-01-26 01:37
As a workaround for #619 : Unable to set default interpreter you may add to *~/.gconf/apps/guake/general/%gconf.xml *
```
        <entry name="default_shell" mtime="1452614719" type="string">
                <stringvalue>/usr/bin/tmux</stringvalue>
        </entry>
```

**Comment by tirkarthi** [comment] 2016-02-21 06:53
@indraforyou @kossa Did you build guake with the latest master? I just checked out the latest master and then tried it. Its working fine. Kindly add in the guake version you are using. The change in value can be seen with `gconftool-2 --get /apps/guake/general/open_tab_cwd` by checking and unchecking the checkbox for the "open new tab in current directory" in the shell tab under guake preferences. Kindly add in the details and please post the `prefs.glade` which I hope can be found at `/usr/share/guake/prefs.glade` to make sure the fix is present.

**Comment by and-dmitry** [comment] 2016-03-25 10:58
There is no schema for `open_tab_cwd` in `guake.schema` in master. Could it be the cause of this problem?

**Comment by tirkarthi** [comment] 2016-03-26 02:14
@and-dimit Thanks for pointing that out. Yes I hope its the source of the problem. I had those schema set and so it was working for me. Others trying to setup Guake fresh might not have the schema created initially. Does anyone know how to uninstall guake or do we have any uninstall script so that I can try to reproduce the same.

**Comment by Davidy22** [comment] 2021-09-16 22:28
open-tab-cwd is now in org.guake.gschema.xml, open tab in current directory setting now works, closing.

**Closed by Davidy22** 2021-09-16 22:28 UTC
Labels: Type: Defect, Priority: High
