### ISSUE TITLE
Guake crashes - Ubuntu 20.04

### ISSUE THREAD

**Issue by tryfon** [Guake/guake#1753] opened 2020-05-07 08:43 UTC
Guake was working fine but at some point started consistently crashing after it starts. No idea what causes it. Find attached my dmesg log. Ubuntu 20.04, Guake 3.7.0 installed through pip3.
[dmesg.txt](https://github.com/Guake/guake/files/4591802/dmesg.txt)

**Comment by alberto-miranda** [comment] 2020-05-07 11:08
The same happens in Ubuntu 19.10, after running fine for more than 4 months. 

The following assertion triggers just before the SEFGAULT:

```bash
/usr/lib/python3/dist-packages/gi/overrides/Gtk.py:1630: Warning: g_object_freeze_notify: assertion 'G_IS_OBJECT (object)' failed
  return _Gtk_main(*args, **kwargs)
Segmentation fault (core dumped)
```

I've checked the `apt` update logs but the only GTK-related packages that have been recently updated are  `libwebkit2gtk-4.0-37`, `libjavascriptcoregtk-4.0-18`, and `gir1.2-javascriptcoregtk-4.0`- Not sure if they are related.

**Comment by nilshg** [comment] 2020-05-10 06:45
I see the same on Manjaro Gnome after updating just now - let me know what info if any I can provide to help debug this.

**Comment by scmanjarrez** [comment] 2020-05-11 16:49
Same in ubuntu 18.04, crash log attached if that helps.

[_usr_bin_guake.1000.crash.log](https://github.com/Guake/guake/files/4610950/_usr_bin_guake.1000.crash.log)

**Comment by cubedtear** [comment] 2020-05-21 16:27
Might be related to https://github.com/Guake/guake/issues/1749#issuecomment-632189285.
Try the "solution" I posted in the linked comment, to see if it works for you.

**Comment by nilshg** [comment] 2020-05-21 16:59
Indeed this did the trick, thanks!

**Comment by ulidtko** [comment] 2020-08-18 10:32
Let me close this as duplicate of #1749.

**Closed by ulidtko** 2020-08-18 10:32 UTC
