### ISSUE TITLE
[UX] Full-width tabs makes scanning tabs harder

### ISSUE THREAD

**Issue by lostfictions** [Guake/guake#962] opened 2017-06-03 00:45 UTC
Hey there. I just updated to 0.8.9, which includes PR #885. Unfortunately, I think the approach of using full-width tabs has a much worse UX than the way tabs worked previously. The issue for me is ease of scanning tabs to read their titles.

When tabs have a maximum width and are left-aligned, it's easy to scan from left-to-right, quickly identify which tab we're on, and read the title. With tabs that share the full screen width and that have centered labels, we first have to identify which tab we're on, and then track to the middle of it -- much further than we would if they were left-aligned.

![1](https://cloud.githubusercontent.com/assets/567041/26749090/da08de18-47d2-11e7-91ff-bf633a830a11.png)

Still, this wouldn't be _too_ bad if we knew the title would always be in the middle of the screen; we could train ourselves to start by looking in the middle. The real issue emerges when we start to add tabs:

![2](https://cloud.githubusercontent.com/assets/567041/26749091/dc28a7fa-47d2-11e7-9dfe-ff9944481cd6.png)

Now, tabs have an indeterminate width, and we have to scan from the edge of the screen to find our current tab -- then potentially track another long distance to find the title. And each tab we add disrupts our ability to remember where the tab we're currently using is -- everything shifts around. The wider the screen, the greater the distance tabs might shift and the more we potentially have to track to find a tab's title.

Incidentally, this is exactly why browsers impose a maximum width on tabs -- it's a good idea that works!

**Comment by Stibbons** [comment] 2017-06-03 12:37
i agree

**Comment by Kharag** [comment] 2017-06-19 08:07
I concur. I suggest to make this setting optional, so people can choose what they prefer :)

**Comment by ipleten** [comment] 2017-06-19 16:02
+1 Please add option to disabled that.

**Comment by garfunkel** [comment] 2017-06-20 07:37
Agreed. I find the new behaviour annoying.

**Comment by Stibbons** [comment] 2017-06-20 08:29
I agree. I think I'll revert it I don't have time to work on optionating it

**Comment by mlouielu** [comment] 2017-06-22 03:17
Ah, so it is a new behavior, not a bug... I don't really like this changed on ArchLinux. Just not good for old user.

**Comment by DaarkWel** [comment] 2017-06-25 16:26
Super annoying. Make it optional plz.

**Comment by kiralex** [comment] 2017-06-26 11:49
Agreed. Hope there will have an option to disable that.

**Comment by naiz0** [comment] 2017-06-27 09:31
i also agree with the other guys. Make it optional plz.

**Comment by lostfictions** [comment] 2017-06-29 17:59
considering this is now the most upvoted issue on the repo -- even more than the four-year-old #71! -- if the devs don't have time right now to add an option for this maybe they could just revert it?

**Comment by narukamiko** [comment] 2017-07-31 02:05
I also agree.

**Comment by RafalSkolasinski** [comment] 2017-08-09 21:50
Reverting sounds good.

**Comment by Stibbons** [comment] 2017-08-10 10:02
Can someone test change on HEAD? I sill haven't retreived my linux workstation to test it

**Comment by lostfictions** [comment] 2017-10-10 01:41
Any chance we could see another release soon now that the revert is merged?

**Comment by Stibbons** [comment] 2017-10-10 11:38
sure ! Working on it asap !

**Comment by Davidy22** [comment] 2022-04-20 04:48
Resolved in #989

**Closed by Davidy22** 2022-04-20 04:48 UTC
