### ISSUE TITLE
Memory leak when maximizing the size and checking "hide tabbar when fullscreen"

### ISSUE THREAD

**Issue by rattit0** [Guake/guake#1789] opened 2020-08-03 21:20 UTC
Hi,

I just found that when I maximizing window size (height & width, not the fullscreen mode), and with the option "hide tabbar when fullscreen" checked, the memory is leaked after I hit F12.
And after several seconds, guake finally showed up with no tabbar --- just like in fullscreen mode (but it was not).
Gnome system monitor show that almost all the RAM and swap was eaten up, and back to normal after a while.
In the meantime I got nothing but "Showing/Hiding the terminal" from `journalctl | grep guake`.
Then my laptop was completely stuck after I tried the second time.

<details><summary>$ guake --support</summary>

Guake Version:		3.7.0

Vte Version:		0.60.3

Vte Runtime Version:	0.60.3

--------------------------------------------------
GTK+ Version:		3.24.21

GDK Backend:		GdkX11.X11Display

--------------------------------------------------
Desktop Session: gnome

--------------------------------------------------
Display: :1

RGBA visual: True

Composited: True

* Monitor: 0 - LGD eDP1
    * Geometry:		1366 x 768 at 0, 0
    * Size:		310 x 170 mm²
    * Primary:		True
    * Refresh rate:	59.99 Hz
    * Subpixel layout:	unknown
</details>

<details><summary>$ ls -1 .local/share/gnome-shell/extensions/</summary>

apps-menu@gnome-shell-extensions.gcampax.github.com
CoverflowAltTab@palatis.blogspot.com
dash-to-dock@micxgx.gmail.com
GmailMessageTray@shuming0207.gmail.com
gsconnect@andyholmes.github.io
hidetopbar@mathieu.bidon.ca
netspeed@hedayaty.gmail.com
no-title-bar@jonaspoehler.de
places-menu@gnome-shell-extensions.gcampax.github.com
system-monitor@paradoxxx.zero.gmail.com
TopIcons@phocean.net
</details>

**Comment by niyoko** [comment] 2021-03-01 02:28
It recently happened to me. Searching issue on google and find this.

**Comment by Davidy22** [comment] 2021-09-15 23:18
Can you give a screenshot of the main window tab in preferences? I can't reproduce this, I have the height and width sliders dragged all the way to the right, displacement in pixels is 0,0 and none of the three horizontal alignment options make it not work.

**Comment by rattit0** [comment] 2021-09-15 23:48
> 
> 
> Can you give a screenshot of the main window tab in preferences? I can't reproduce this, I have the height and width sliders dragged all the way to the right, displacement in pixels is 0,0 and none of the three horizontal alignment options make it not work.

I'm sorry that I can't reproduce it now either. I switched to kde plasma after gnome updating to version 40. So I'm using yakuake now.

**Comment by Davidy22** [comment] 2021-09-16 00:38
RIP. Well, can't reproduce and there's been a fair bit of changes in git main that may have cleared this up in the meantime. Python updates are fairly relevant too, we aren't actually doing any memory management, python handles this for us and it may be that the python of sept 2021 fixed the memory leak that caused this in april 2020. Closing because none of us can reproduce anymore, but will await future reports of this if it still occurs.

**Closed by Davidy22** 2021-09-16 00:38 UTC
Labels: Type: Defect, Type: Need More Info
