### ISSUE TITLE
Guake no longer starts on Arch, core dump

### ISSUE THREAD

**Issue by Edojp** [Guake/guake#1784] opened 2020-07-16 03:37 UTC
As of today guake, is no longer launching. Running Arch linux on kernel 5.7.8, Gnome 3.36.4. Console, journalctl output below.

Please take a look. Many thanks.

```
$ guake
Guake not running, starting it
Loading Gnome schema from: /usr/share/glib-2.0/schemas
Language previously loaded from: /usr/share/locale
Guake Terminal 3.7.0
VTE 0.60.3
Gtk 3.24.21
created fresh notebook for workspace 0
Spawning new terminal at /home/edo
current workspace is 0
can't bind show-focus key
Spawning new terminal at /home/edo/builds/android-studio
Spawning new terminal at /home/edo/builds/android-studio
Spawning new terminal at /home/edo/builds/android-studio
Spawning new terminal at /home/edo/builds/android-studio
Guake tabs restored from /home/edo/.config/guake/session.json
Guake initialized
Guake tabs saved to /home/edo/.config/guake/session.json
**
VTE:ERROR:../vte/src/vte.cc:3336:void vte::terminal::Terminal::process_incoming(): code should not be reached
Bail out! VTE:ERROR:../vte/src/vte.cc:3336:void vte::terminal::Terminal::process_incoming(): code should not be reached
Aborted (core dumped)`


`7月 16 12:29:41 exps13arch systemd-coredump[1354]: Process 1331 (guake) of user 1000 dumped core.
                                                     
                                                     Stack trace of thread 1331:
                                                     #0  0x00007faa6a146d86 n/a (libvte-2.91.so.0 + 0x2bd86)
                                                     #1  0x00007faa6a1486d8 n/a (libvte-2.91.so.0 + 0x2d6d8)
                                                     #2  0x00007faa6a14879f n/a (libvte-2.91.so.0 + 0x2d79f)
                                                     #3  0x00007faa6a148ae1 n/a (libvte-2.91.so.0 + 0x2dae1)
                                                     #4  0x00007faa6c916764 n/a (libglib-2.0.so.0 + 0x52764)
                                                     #5  0x00007faa6c916340 g_main_context_dispatch (libglib-2.0.so.0 + 0x52340)
                                                     #6  0x00007faa6c9641d9 n/a (libglib-2.0.so.0 + 0xa01d9)
                                                     #7  0x00007faa6c914c03 g_main_loop_run (libglib-2.0.so.0 + 0x50c03)
                                                     #8  0x00007faa6b24e08f gtk_main (libgtk-3.so.0 + 0x1e008f)
                                                     #9  0x00007faa6c844a8d n/a (libffi.so.7 + 0x6a8d)
                                                     #10 0x00007faa6c84401b n/a (libffi.so.7 + 0x601b)
                                                     #11 0x00007faa6ca473a2 n/a (_gi.cpython-38-x86_64-linux-gnu.so + 0x1a3a2)
                                                     #12 0x00007faa6ca46982 n/a (_gi.cpython-38-x86_64-linux-gnu.so + 0x19982)
                                                     #13 0x00007faa6d750e6c PyObject_Call (libpython3.8.so.1.0 + 0x141e6c)
                                                     #14 0x00007faa6d72eda5 _PyEval_EvalFrameDefault (libpython3.8.so.1.0 + 0x11fda5)
                                                     #15 0x00007faa6d72b654 _PyEval_EvalCodeWithName (libpython3.8.so.1.0 + 0x11c654)
                                                     #16 0x00007faa6d73d87d _PyFunction_Vectorcall (libpython3.8.so.1.0 + 0x12e87d)
                                                     #17 0x00007faa6d731635 _PyEval_EvalFrameDefault (libpython3.8.so.1.0 + 0x122635)
                                                     #18 0x00007faa6d73d7e8 _PyFunction_Vectorcall (libpython3.8.so.1.0 + 0x12e7e8)
                                                     #19 0x00007faa6d72cd08 _PyEval_EvalFrameDefault (libpython3.8.so.1.0 + 0x11dd08)
                                                     #20 0x00007faa6d72b654 _PyEval_EvalCodeWithName (libpython3.8.so.1.0 + 0x11c654)
                                                     #21 0x00007faa6d7dbb03 PyEval_EvalCode (libpython3.8.so.1.0 + 0x1ccb03)
                                                     #22 0x00007faa6d7e7248 n/a (libpython3.8.so.1.0 + 0x1d8248)
                                                     #23 0x00007faa6d7e1483 n/a (libpython3.8.so.1.0 + 0x1d2483)
                                                     #24 0x00007faa6d6a13f8 PyRun_FileExFlags (libpython3.8.so.1.0 + 0x923f8)
                                                     #25 0x00007faa6d6a0e8a PyRun_SimpleFileExFlags (libpython3.8.so.1.0 + 0x91e8a)
                                                     #26 0x00007faa6d7f41e2 Py_RunMain (libpython3.8.so.1.0 + 0x1e51e2)
                                                     #27 0x00007faa6d7d03d9 Py_BytesMain (libpython3.8.so.1.0 + 0x1c13d9)
                                                     #28 0x00007faa6d46f002 __libc_start_main (libc.so.6 + 0x27002)
                                                     #29 0x000055c6211f604e _start (python3.8 + 0x104e)
                                                     
                                                     Stack trace of thread 1335:
                                                     #0  0x00007faa6d53d05f __poll (libc.so.6 + 0xf505f)
                                                     #1  0x00007faa6c964168 n/a (libglib-2.0.so.0 + 0xa0168)
                                                     #2  0x00007faa6c914c03 g_main_loop_run (libglib-2.0.so.0 + 0x50c03)
                                                     #3  0x00007faa6c70f1a8 n/a (libgio-2.0.so.0 + 0x1001a8)
                                                     #4  0x00007faa6c93e511 n/a (libglib-2.0.so.0 + 0x7a511)
                                                     #5  0x00007faa6d42f422 start_thread (libpthread.so.0 + 0x9422)
                                                     #6  0x00007faa6d547bf3 __clone (libc.so.6 + 0xffbf3)
                                                     
                                                     Stack trace of thread 1338:
                                                     #0  0x00007faa6d54271d syscall (libc.so.6 + 0xfa71d)
                                                     #1  0x00007faa6c95ec9b g_cond_wait_until (libglib-2.0.so.0 + 0x9ac9b)
                                                     #2  0x00007faa6c8e6803 n/a (libglib-2.0.so.0 + 0x22803)
                                                     #3  0x00007faa6c942d5b n/a (libglib-2.0.so.0 + 0x7ed5b)
                                                     #4  0x00007faa6c93e511 n/a (libglib-2.0.so.0 + 0x7a511)
                                                     #5  0x00007faa6d42f422 start_thread (libpthread.so.0 + 0x9422)
                                                     #6  0x00007faa6d547bf3 __clone (libc.so.6 + 0xffbf3)
                                                     
                                                     Stack trace of thread 1333:
                                                     #0  0x00007faa6d53d05f __poll (libc.so.6 + 0xf505f)
                                                     #1  0x00007faa6c964168 n/a (libglib-2.0.so.0 + 0xa0168)
                                                     #2  0x00007faa6c915221 g_main_context_iteration (libglib-2.0.so.0 + 0x51221)
                                                     #3  0x00007faa6c915272 n/a (libglib-2.0.so.0 + 0x51272)
                                                     #4  0x00007faa6c93e511 n/a (libglib-2.0.so.0 + 0x7a511)
                                                     #5  0x00007faa6d42f422 start_thread (libpthread.so.0 + 0x9422)
                                                     #6  0x00007faa6d547bf3 __clone (libc.so.6 + 0xffbf3)
                                                     
                                                     Stack trace of thread 1334:
                                                     #0  0x00007faa6d53d05f __poll (libc.so.6 + 0xf505f)
                                                     #1  0x00007faa6c964168 n/a (libglib-2.0.so.0 + 0xa0168)
                                                     #2  0x00007faa6c915221 g_main_context_iteration (libglib-2.0.so.0 + 0x51221)
                                                     #3  0x00007faa67b64e5e n/a (libdconfsettings.so + 0x4e5e)
                                                     #4  0x00007faa6c93e511 n/a (libglib-2.0.so.0 + 0x7a511)
                                                     #5  0x00007faa6d42f422 start_thread (libpthread.so.0 + 0x9422)
                                                     #6  0x00007faa6d547bf3 __clone (libc.so.6 + 0xffbf3)
                                                     
                                                     Stack trace of thread 1339:
                                                     #0  0x00007faa6d54271d syscall (libc.so.6 + 0xfa71d)
                                                     #1  0x00007faa6c95ec9b g_cond_wait_until (libglib-2.0.so.0 + 0x9ac9b)
                                                     #2  0x00007faa6c8e6803 n/a (libglib-2.0.so.0 + 0x22803)
                                                     #3  0x00007faa6c942d5b n/a (libglib-2.0.so.0 + 0x7ed5b)
                                                     #4  0x00007faa6c93e511 n/a (libglib-2.0.so.0 + 0x7a511)
                                                     #5  0x00007faa6d42f422 start_thread (libpthread.so.0 + 0x9422)
                                                     #6  0x00007faa6d547bf3 __clone (libc.so.6 + 0xffbf3)
-- Subject: Process 1331 (guake) dumped core
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- Documentation: man:core(5)
-- 
-- Process 1331 (guake) crashed and dumped core.
```

**Comment by dgaus** [comment] 2020-07-17 13:16
Had this same issue, seems to be caused by the "restore previous session" startup option. I didn't investigate much but disabling all three "Startup & Tabs" options fixes the issue.

**Comment by idiot-z** [comment] 2020-07-17 18:55
Hi, I have the same issue. Same error showing with journalctl.

I just realized that it only crashes when several tabs are saved in `$HOME/.config/guake/session.json`. If I manually remove one tab in this file, then it works again.

**Comment by Edojp** [comment] 2020-07-19 09:10
Thanks both it does indeed launch after I deleted session.json

**Comment by ulidtko** [comment] 2020-07-20 08:42
Please see #1641; I'm closing all the duplicate issues.

**Closed by ulidtko** 2020-07-20 08:42 UTC
