### ISSUE TITLE
Guake is folded automaticlly when mouse click other place.

### ISSUE THREAD

**Issue by couragelfyang** [Guake/guake#997] opened 2017-09-10 01:06 UTC
When mouse chlicks other place, the guake window is folded automaticlly and does not stay on the top. That's why? It is not convenient that I must toggle F12 again to drop down it. Is there any method to fix it?

My environment:
Kerel Version: Archlinux 4.12.10-1 x86_64
KDE Plasma Version: 5.10.5
KDE Frameworks version: 5.37.0
Qt Version 5.9.1

**Comment by MRebhan** [comment] 2017-09-22 14:05
Disable "Hide on lost focus" in the settings

**Comment by Davidy22** [comment] 2022-04-20 04:47
Not a bug, closing.

**Closed by Davidy22** 2022-04-20 04:47 UTC
