### ISSUE TITLE
Guake wont come out

### ISSUE THREAD

**Issue by simlevesque** [Guake/guake#469] opened 2015-02-27 00:25 UTC
As soon as I press the Guake shortcut, guake pops up then disappears immediately. I'm running Linux Mint 17.1 with xfce, nvidia's proprietary drivers. Here is a dump of the output of the command aptitude search '~i!~M'
http://pastebin.com/raw.php?i=6eb1vWvH

It was working yesterday.

**Comment by simlevesque** [comment] 2015-02-27 01:46
The problem comes from the fact the my tmux is not working.

**Comment by simlevesque** [comment] 2015-02-27 01:50
My tmux started to work again... for no reason. I did not touch the config file. The bug exists, gives no explanation and might come up again so you might want to leave it open.

**Comment by Stibbons** [comment] 2015-02-28 11:02
ok. Noted

**Comment by gsemet** [comment] 2018-04-16 19:18
which version of guake?

**Comment by extraymond** [comment] 2018-04-17 06:00
Guake 3.0.5 with gnome-shell.

The symptoms is below:

1. When selecting byobu or tmux, guake will flashed for half a second after pressing hot-key (ctrl-f12) 
2. Causing gnome-shell to have overloading cpu usage.

I think something was causing a dead loop.
Hope this helps!

**Comment by aichingm** [comment] 2018-09-21 14:47
@gsemet can we close this issue since the solution to the problem is to not set the l*ogin* option?

**Comment by gsemet** [comment] 2018-09-21 15:37
maybe we can have a better failure handling instead of flashing everywhere

**Comment by aichingm** [comment] 2018-09-21 15:39
something like a fallback to bash and a log message? would that be ok?

**Comment by gsemet** [comment] 2018-09-21 18:02
Or maybe, in the pref panel, we add a label saying some shell does not have --login and may break this feature.
But sure, in case of crash, we need to fallback to bash and add a dialog box (something annoying enough so the user need to correct it) telling the --login crashed

**Comment by aichingm** [comment] 2018-09-21 20:53
I just tested this with `/usr/bin/tmux --login` and it fails obviously but guke works fine and just shows the tmux error. 

![image](https://user-images.githubusercontent.com/6470959/45905494-d0578f00-bdf0-11e8-9269-a54f08c9c450.png)

I will just add a label to the prefs.

**Closed** 2018-10-02 10:58 UTC
Labels: Priority: URGENT, Type: Defect
