### ISSUE TITLE
copy text on selection

### ISSUE THREAD

**Issue by kurokirasama** [Guake/guake#1898] opened 2021-09-13 20:36 UTC
Hello,

it would be nice to be able to copy a text only by selecting it... if this is a feature, I'm sorry but haven't found the option to enable it

**Comment by Davidy22** [comment] 2021-09-14 01:43
The standard linux behavior for copying on select is to put the selected text in the middle click button's clipboard. If you select some text and middle click on something in guake, you should see that this works as intended. Unless you wanted guake to put selected text in the CTRL+V clipboard? This would be a bit outside standard behavior for linux.

**Comment by kurokirasama** [comment] 2021-09-14 05:27
Hi, thanks for your response... It might not be the standard but is what I'm used to on my previous terminal... I found yours and switched, it's really is a great improvement to productivity... now, it just a suggestion, you might add it or not... if it's easy to implement, why not? 
Regards,

**Comment by Davidy22** [comment] 2021-09-14 05:49
Well, think this should be doable. Can take a shot at it

**Comment by kurokirasama** [comment] 2021-09-14 17:45
cool!! thanks!! yup, optional is the way

**Comment by Davidy22** [comment] 2021-09-15 14:18
While making the pull request I found out that #43 exists, so closing this because duplicate but the feature is in the pull request pipeline now.

**Closed by Davidy22** 2021-09-15 14:18 UTC
