### ISSUE TITLE
Guake does not slide down when called

### ISSUE THREAD

**Issue by TinyBabyOwl** [Guake/guake#1659] opened 2019-10-08 09:06 UTC
**Describe the bug**

When summoning Guake it zooms instead of sliding down from the top

**Expected behavior**

When summoning Guake it should slide down from the top like the Quake console.

-------------------------------------------------------------------------------

<details><summary>$ guake --support</summary>

Guake Version:		3.6.3

Vte Version:		0.56.3

Vte Runtime Version:	0.56.3

--------------------------------------------------
GTK+ Version:		3.24.10

GDK Backend:		GdkX11.X11Display

--------------------------------------------------
Desktop Session: gnome

--------------------------------------------------
Display: :1

RGBA visual: True

Composited: True

* Monitor: 0 -  DP-4
    * Geometry:		2560 x 1440 at 3440, 0
    * Size:		597 x 336 mm²
    * Primary:		True
    * Refresh rate:	143.85 Hz
    * Subpixel layout:	unknown
* Monitor: 1 -  DP-2
    * Geometry:		3440 x 1440 at 0, 0
    * Size:		800 x 335 mm²
    * Primary:		False
    * Refresh rate:	75.05 Hz
    * Subpixel layout:	unknown

**Comment by Davidy22** [comment] 2021-09-05 01:49
Closing because duplicate of #701

**Closed by Davidy22** 2021-09-05 01:49 UTC
