### ISSUE TITLE
Segmentation fault on application startup.

### ISSUE THREAD

**Issue by Sadario** [Guake/guake#1740] opened 2020-03-23 10:06 UTC
I am running Arch on this laptop, with a mate desktop environment. Below are the relevant outputs from 'journalctl' and 'guake --support', as well as the contents of the session.json-file. I have also tried running 'guake -u', which does not change the behaviour.

Deleting/renaming '~/.config/guake/session.json' solves the problem temporarily. Guake now starts, but after a clean shutdown of the application, it will not start again.

I really hope someone can help me with this issue, as I would love to get back to using this brilliant software.

<details><summary>~/.config/guake/session.json</summary>
{
    "schema_version": 2,
    "timestamp": 1584957548,
    "workspace": {
        "0": [
            [
                {
                    "panes": [
                        {
                            "type": "term",
                            "directory": "/home/sadario",
                            "custom_colors": {
                                "fg_color": null,
                                "bg_color": null,
                                "palette": null
                            }
                        }
                    ],
                    "label": "sadario@sadario-arch: ~",
                    "custom_label_set": false
                }
            ]
        ]
    }
}
</details>

<details><summary>$ journalctl</summary>
Process 6386 (guake) of user 1000 dumped core.
      
      Stack trace of thread 6386:
      #0  0x00007f9967760cbf n/a (libvte-2.91.so.0 + 0x2bcbf)
      #1  0x00007f9967760e11 n/a (libvte-2.91.so.0 + 0x2be11)
      #2  0x00007f996f821684 n/a (libglib-2.0.so.0 + 0x66684)
      #3  0x00007f996f82688f g_main_context_dispatch (libglib-2.0.so.0 + 0x6b88f)
      #4  0x00007f996f828831 n/a (libglib-2.0.so.0 + 0x6d831)
      #5  0x00007f996f829843 g_main_loop_run (libglib-2.0.so.0 + 0x6e843)
      #6  0x00007f996e08f94f gtk_main (libgtk-3.so.0 + 0x28394f)
      #7  0x00007f996f73569a ffi_call_unix64 (libffi.so.6 + 0x669a)
      #8  0x00007f996f734fb6 ffi_call (libffi.so.6 + 0x5fb6)
      #9  0x00007f996f8fd3a2 n/a (_gi.cpython-38-x86_64-linux-gnu.so + 0x1a3a2)
      #10 0x00007f996f8fc982 n/a (_gi.cpython-38-x86_64-linux-gnu.so + 0x19982)
      #11 0x00007f997037afc0 PyObject_Call (libpython3.8.so.1.0 + 0x13bfc0)
      #12 0x00007f997042fde7 _PyEval_EvalFrameDefault (libpython3.8.so.1.0 + 0x1f0de7)
      #13 0x00007f997041df34 _PyEval_EvalCodeWithName (libpython3.8.so.1.0 + 0x1def34)
      #14 0x00007f997041f2bb _PyFunction_Vectorcall (libpython3.8.so.1.0 + 0x1e02bb)
      #15 0x00007f9970432542 _PyEval_EvalFrameDefault (libpython3.8.so.1.0 + 0x1f3542)
      #16 0x00007f997041f0dd _PyFunction_Vectorcall (libpython3.8.so.1.0 + 0x1e00dd)
      #17 0x00007f997042de6c _PyEval_EvalFrameDefault (libpython3.8.so.1.0 + 0x1eee6c)
      #18 0x00007f997041df34 _PyEval_EvalCodeWithName (libpython3.8.so.1.0 + 0x1def34)
      #19 0x00007f99704a5873 PyEval_EvalCode (libpython3.8.so.1.0 + 0x266873)
      #20 0x00007f99704a58c8 n/a (libpython3.8.so.1.0 + 0x2668c8)
      #21 0x00007f99704a9ba3 n/a (libpython3.8.so.1.0 + 0x26aba3)
      #22 0x00007f9970344a1f PyRun_FileExFlags (libpython3.8.so.1.0 + 0x105a1f)
      #23 0x00007f997034e6d7 PyRun_SimpleFileExFlags (libpython3.8.so.1.0 + 0x10f6d7)
      #24 0x00007f99704b635e Py_RunMain (libpython3.8.so.1.0 + 0x27735e)
      #25 0x00007f99704b6449 Py_BytesMain (libpython3.8.so.1.0 + 0x277449)
      #26 0x00007f9970626023 __libc_start_main (libc.so.6 + 0x27023)
      #27 0x000055925e1cd05e _start (python3.8 + 0x105e)
      
      Stack trace of thread 6391:
      #0  0x00007f99706f3abf __poll (libc.so.6 + 0xf4abf)
      #1  0x00007f996f8287a0 n/a (libglib-2.0.so.0 + 0x6d7a0)
      #2  0x00007f996f828871 g_main_context_iteration (libglib-2.0.so.0 + 0x6d871)
      #3  0x00007f996f8288c2 n/a (libglib-2.0.so.0 + 0x6d8c2)
      #4  0x00007f996f7ffe71 n/a (libglib-2.0.so.0 + 0x44e71)
      #5  0x00007f997022646f start_thread (libpthread.so.0 + 0x946f)
      #6  0x00007f99706fe3d3 __clone (libc.so.6 + 0xff3d3)
      
      Stack trace of thread 6392:
      #0  0x00007f99706f3abf __poll (libc.so.6 + 0xf4abf)
      #1  0x00007f996f8287a0 n/a (libglib-2.0.so.0 + 0x6d7a0)
      #2  0x00007f996f829843 g_main_loop_run (libglib-2.0.so.0 + 0x6e843)
      #3  0x00007f996f55edf8 n/a (libgio-2.0.so.0 + 0x59df8)
      #4  0x00007f996f7ffe71 n/a (libglib-2.0.so.0 + 0x44e71)
      #5  0x00007f997022646f start_thread (libpthread.so.0 + 0x946f)
      #6  0x00007f99706fe3d3 __clone (libc.so.6 + 0xff3d3)
      
      Stack trace of thread 6393:
      #0  0x00007f99706f3abf __poll (libc.so.6 + 0xf4abf)
      #1  0x00007f996f8287a0 n/a (libglib-2.0.so.0 + 0x6d7a0)
      #2  0x00007f996f828871 g_main_context_iteration (libglib-2.0.so.0 + 0x6d871)
      #3  0x00007f9965205e5e n/a (libdconfsettings.so + 0x4e5e)
      #4  0x00007f996f7ffe71 n/a (libglib-2.0.so.0 + 0x44e71)
      #5  0x00007f997022646f start_thread (libpthread.so.0 + 0x946f)
      #6  0x00007f99706fe3d3 __clone (libc.so.6 + 0xff3d3)
</details>

<details><summary>$ dmesg</summary>
[ 3673.001752] guake[8884]: segfault at 19 ip 00007f561394dcbf sp 00007ffc039297e0 error 4 in libvte-2.91.so.0.6000.0[7f5613931000+48000]
[ 3673.001767] Code: fd 53 48 8b 87 08 01 00 00 89 f3 48 85 c0 74 32 80 bf 18 01 00 00 00 75 0a 8b 97 10 01 00 00 85 d2 75 17 c6 85 18 01 00 00 00 <8b> 70 18 ba 01 00 00 00 48 89 ef e8 c1 1b ff ff 48 89 ef e8 39 19
</details>

<details><summary>$ guake --support</summary>

Guake Version:		3.7.0

Vte Version:		0.60.0

Vte Runtime Version:	0.60.0

--------------------------------------------------
GTK+ Version:		3.24.14

GDK Backend:		GdkX11.X11Display

--------------------------------------------------
Desktop Session: mate

--------------------------------------------------
Display: :0

RGBA visual: True

Composited: True

* Monitor: 0 - AUO eDP1
    * Geometry:		1920 x 1080 at 0, 0
    * Size:		310 x 170 mm²
    * Primary:		True
    * Refresh rate:	60.05 Hz
    * Subpixel layout:	unknown

**Comment by dniku** [comment] 2020-03-24 11:19
Seems to be a duplicate of https://github.com/Guake/guake/issues/1739.

**Comment by samuelvanderwaal** [comment] 2020-03-27 00:16
@Sadario unchecking the experimental startup and restore tab options seems to fix this problem for me. 

![Selection_070](https://user-images.githubusercontent.com/1684605/77708501-1c9f0480-6f7d-11ea-9bdc-adec6df995ba.png)

**Comment by Sadario** [comment] 2020-03-27 00:19
With limited testing, I can also confirm that this seems to fix the issue.

**Comment by fennectech** [comment] 2020-04-05 23:10
Deleting session.json fixes it.   I am able to trigger this bug by killing guake or running it in another terminal and killing it with ctrl C.   The result the segfult   deleting session.json lets you start the application again

**Comment by ulidtko** [comment] 2020-07-20 09:02
Hey, thanks for nice report; however let me close this as duplicate of #1641 and #1749 (which are both the exact same issue, i.e. dupes, too).

**Closed by ulidtko** 2020-07-20 09:02 UTC
