### ISSUE TITLE
Name of tabs must be of static size, otherwise is a nigthmare

### ISSUE THREAD

**Issue by kikecalpe** [Guake/guake#54] opened 2013-04-17 18:27 UTC
Name of tabs must be of static size, otherwise is a nigthmare
http://guake.org/ticket/493
Reported by: 	jorgeecardona 	Owned by: 	somebody
Priority: 	major 	Milestone: 	0.5.0
Component: 	guake 	Version: 	
Keywords: 		Cc: 	
Description

Hi,

A new feature in guake put the current path in the console as the name of the tab, but this is a pain since:

1. If you were used to have more than 10 open tabs, now you will be able to use just 4 or 5.

2. Even with one tab if you are in a deep path the name will fill the whole bottom section, and you will see just one tab.

I don't really know why someone hates a single "Terminal 1", but there must be an option to maintain this behaviour, a single checkbox for the crazy guys like me that loves the "Terminal x" name would be of really help.

Bye.

**Comment by Stibbons** [comment] 2015-04-28 14:26
Duplicate of #47

**Closed by Stibbons** 2015-04-28 14:26 UTC
Labels: Type: Feature Request
