### ISSUE TITLE
Fullscreen toggle not always goes back to old state

### ISSUE THREAD

**Issue by Lowrida** [Guake/guake#1936] opened 2021-10-18 15:04 UTC
I noticed that the fullscreen toggle not always goes back to the old state.

Press F12 normal state, press F11 to fullscreen, press F11 again goes to old state.
But..
Press F12 normal state, press F11 to fullscreen, press F12 twice to hide and un-hide and then press F11 does not get me the old state. I have to press F12 twice again to get the old state back!

Hope this makes sence..

**Comment by Davidy22** [comment] 2021-10-18 15:36
Oh wait actually noticed I was on the test branch for window decorations that just seems to accidentally fix this which'll be nice for when I get that finished. Also found #1485 which this looks like a duplicate of, so closing this issue.

**Closed as completed by Davidy22** 2021-10-18 15:36 UTC
