### ISSUE TITLE
Adding Font ligatures

### ISSUE THREAD

**Issue by egon69** [Guake/guake#2244] opened 2024-04-11 01:21 UTC
Be sure to check the existing issues (both open and closed!), and make sure you are running the latest version of Guake.

For how to run the latest Guake in your computer, please refer to [Install from source](https://guake.readthedocs.io/en/latest/user/installing.html#install-from-source).

---------------------------------------

Please use [FeatHub](https://feathub.com/Guake/guake) to fill-up a feature request.

This allows us to spot directly which are the most requested features.

I have checked open and closed issues and haven't really seen anything about it.. I don't know if it's possible utilizing VTE, but is there a way to utilize font ligatures?

**Comment by novaTopFlex** [comment] 2024-04-30 16:58
The Guake drop-down terminal is intended to be a terminal-emulator, so system fonts should be set to monospace. By adding font ligatures, we are defeating the purpose of the terminal emulator, and the computer code may no longer be recognized properly. (I assume that you are speaking about fi, fl, ffi, ffl, etc.)

**Comment by Davidy22** [comment] 2024-05-31 17:52
This issue is essentially #1649. The title of this issue is a little more descriptive of the functional ask than the other one, though I do feel like the issue body of the other one is quite nicely written. Still an effective duplicate of the other one so ultimately closing this one, though I do wish the older issue had a title closer to the base issue like this one.

**Closed by Davidy22** 2024-05-31 17:52 UTC
