### ISSUE TITLE
Opens in wrong monitor in gnome wayland with mutter

### ISSUE THREAD

**Issue by dnut** [Guake/guake#2141] opened 2022-11-11 13:59 UTC
**Describe the bug**

I use a custom keyboard shortcut in gnome to execute `guake-toggle`, which usually opens on the wrong monitor. It does not open on the monitor with my mouse cursor. It does not open on the monitor with the active window. It seems to pick randomly.

Guake is configured to "Appear on mouse display." I have three monitors. It sometimes opens on monitor 1, usually on monitor 2, and never on 3. I haven't been able to figure out how it decides what monitor to open on. But usually it sticks to one monitor for a while. I can click around both monitors and open and close different windows in different monitors, but it will keep opening in the same monitor over and over. Hours later I'll try again and it may or may not start opening on a different monitor.

Currently I'm running gnome 43.0 but I also had the same issue with 42. I have gnome configured to focus on hover.

**Expected behavior**

guake opens on the monitor that has my mouse cursor

**Actual behavior**

guake opens on some other monitor

**To Reproduce**

1. run a gnome wayland session with three monitors
2. enable "Appear on mouse display" in guake
3. execute guake-toggle

-------------------------------------------------------------------------------
<details><summary>$ guake --support</summary>

Guake Version:		3.9.1.dev0

Vte Version:		0.70.1

Vte Runtime Version:	0.70.1

--------------------------------------------------
GTK+ Version:		3.24.34

GDK Backend:		<GdkX11.X11Display

--------------------------------------------------
Desktop Session: gnome

--------------------------------------------------
Display: :0

RGBA visual: True

Composited: True

* Monitor: 0 - XWAYLAND3
    * Geometry:		1920 x 1080 at 3072, 1612
    * Size:		310 x 170 mm²
    * Primary:		True
    * Refresh rate:	59.962 Hz
    * Subpixel layout:	unknown
* Monitor: 1 - XWAYLAND1
    * Geometry:		1920 x 1080 at 4992, 1612
    * Size:		340 x 190 mm²
    * Primary:		False
    * Refresh rate:	59.876000000000005 Hz
    * Subpixel layout:	unknown
* Monitor: 2 - XWAYLAND2
    * Geometry:		3072 x 1728 at 0, 0
    * Size:		600 x 340 mm²
    * Primary:		False
    * Refresh rate:	59.941 Hz
    * Subpixel layout:	unknown

**Comment by hackedd** [comment] 2022-11-22 12:55
Duplicate of #2115.

**Closed by hackedd** 2022-11-22 12:55 UTC

**Comment by anhtumai** [comment] 2026-08-22 07:18
> This is a Wayland/XWayland issue with how Guake queries the pointer position -> on Wayland sessions Guake runs under XWayland (GDK Backend: X11Display in the support dumps above), and X11 pointer queries only get updated when the cursor is over an XWayland-backed window. That matches exactly what's reported here: it works while hovering XWayland apps and "sticks" to the last monitor seen once the cursor moves over a native Wayland surface. Here's a working solution for GNOME/Mutter-based Wayland sessions - a GNOME Shell extension that reads the pointer position directly from the compositor instead of relying on Guake's own X11-based detection, and moves the Guake window to the correct monitor whenever it's shown: https://github.com/adam8kac/guake-follow-cursor
> 
> Won't help on non-GNOME compositors since it's a shell extension, but it fully resolves the "sticks to last monitor" behavior on GNOME Wayland.

I think @adam8kac answers the reason correctly here

**Comment by anhtumai** [comment] 2026-08-22 08:19
for people using GNome, in order to deal with this in current codebase, you can use shortcut to manually move Guake drop-down terminal to others monitors: https://discourse.gnome.org/t/gnome-shortcut-key-to-move-window-to-next-monitor/15260
Super(Window) + Shift + Arrow key shortcut works for me.
