### ISSUE TITLE
Guake does not appear at right position in Gnome 3.30.2 Wayland

### ISSUE THREAD

**Issue by delbato** [Guake/guake#1489] opened 2019-01-17 14:46 UTC
Guake version:

    Guake Terminal: 3.4.0
    VTE: 0.54.3
    VTE runtime: 0.54.3
    Gtk: 3.24.3

Gnome version: `3.30.2`
OS/Distribution: Arch Linux
GPU driver: `amdgpu`

The title says it: Guake, with the "Appear on mouse cursor" option set, does never appear at the correct position. The window simply appears and reappears on the internal laptop and external primary monitors, but never directly on the monitor the mouse is hovering on

**Comment by vkomodey** [comment] 2019-01-21 11:10
The same for me.
```
Kernel - V4.14.91-1-MANJARO
OS - Manjaro Linux.
DE -  Gnome V3.30.2
```

```
Guake Terminal: 3.4.0
VTE: 0.54.3
VTE runtime: 0.54.3
Gtk: 3.24.2
```

I have one external monitor. After I open the Guake instance for the first time it appears on the first monitor, the second time on the second. Frankly speaking, it is pretty annoying, because I'm using guake as a main terminal

**Comment by mgvazquez** [comment] 2019-02-05 15:51
Same here

Kernel: 4.20.5-100.fc28.x86_64
OS: Fedora release 28 (Twenty Eight)
DE: Gnome 3.28.2

Guake Terminal: 3.4.1
VTE: 0.52.2
VTE runtime: 0.52.2
Gtk: 3.22.30

**Comment by amezin** [comment] 2019-02-15 22:48
AFAIK Guake has no special code path for Wayland, and even forcibly selects X11 GDK backend, so it's most likely a bug in Mutter.
Yes, I'm seeing the same behavior on 3.30.2, Arch.

**Comment by fthzkrtn** [comment] 2019-04-08 13:48
Same here :+1:

**Comment by Saucistophe** [comment] 2022-04-08 12:29
In Ubuntu 22.04 beta, it works if my cursor is above certain apps: chrome, vs code, intelliJ Idea...
...Not over the desktop, the file manager, nor Firefox.

Here is a low-res demo of the problem.
![Screencast from 08-04-2022 14_13_45](https://user-images.githubusercontent.com/7082839/162435641-79fb7b36-38fd-4883-a0eb-0236db515a14.gif)
!

**Comment by Saucistophe** [comment] 2022-04-20 07:29
...And it's gone. Everything works fine on the latest Ubuntu beta with the latest Guake!

**Comment by Davidy22** [comment] 2022-04-20 08:31
This is still the 22.04 beta? Do you have an idea of which packages changed for you to resolve this?

**Comment by Saucistophe** [comment] 2022-04-20 10:06
Still the beta yes.
I have no clue, I like my OS as I like my coffee: Fresh, and fixed by someone else :smile: 

![image](https://user-images.githubusercontent.com/7082839/164204413-2012e815-87b4-43f2-9b28-b97a78cb496c.png)

**Comment by Davidy22** [comment] 2022-04-20 10:24
The launchpad timestamp for the last updated Guake package says 2022-02-25 so I doubt you received a Guake update. Seeing as I've been unable to reproduce this, I can believe a package somewhere else in the stack being the cause of this that was fixed.

**Closed by Davidy22** 2022-04-20 10:24 UTC
