### ISSUE TITLE
Tray icon

### ISSUE THREAD

**Issue by alabotski** [Guake/guake#1623] opened 2019-07-07 06:42 UTC
Linux Mint 19.1 Cinnamon
So icon is displayed in the tray

![image](https://user-images.githubusercontent.com/439337/60764960-8c8df780-a09b-11e9-86f0-72c96a6c1323.png)

**Comment by ivoshm** [comment] 2019-07-08 12:55
Probably duplicate with  #1110.

**Comment by gsemet** [comment] 2019-07-09 19:25
do you have hires screen?

**Comment by alabotski** [comment] 2019-07-10 14:22
What screen?

**Comment by Davidy22** [comment] 2021-09-05 00:22
Closing because of duplicate of #1110, provide updates in that bug report if more information can be contributed.

**Closed by Davidy22** 2021-09-05 00:22 UTC
