### ISSUE TITLE
'clear' Messes Up Scrolling

### ISSUE THREAD

**Issue by UnsolvedCypher** [Guake/guake#308] opened 2014-03-30 16:54 UTC
When running the 'clear' command or other commands which add newlines to the output, guake scrolls up or down while hidden. For example, try running the 'clear' command, hiding guake, then showing guake again. The terminal prompt is no longer visible until you press a key, when it scrolls back into view. This only happens in fullscreen for me.

**Comment by manoevis** [comment] 2015-01-13 10:04
I've commented https://github.com/Guake/guake/issues/438#issuecomment-69570644 - but actually this is issue is what I'm facing now.

Env: fedora21, x64, all updates(kernel 3.17.8, mesa10.4 Intel HD Graphics(haswell), gnome shell 3.14.3)

when hide/show fullscreen guake scrolls up one line all the time.

1. Pic. Here is no hide/show.
![1](https://cloud.githubusercontent.com/assets/5586135/5718956/da6814ac-9b1b-11e4-88f1-08dadbc0e34d.png)

2. Pic. Here after many hide/show. Note: you can't see terminal's PS and empty line scrolls up whatsoever.
![2](https://cloud.githubusercontent.com/assets/5586135/5718985/1d3f7022-9b1c-11e4-9f4b-76ed0581c2d2.png)

3. Pic. Hit spacebar and you get back your lines in terminal.
![3](https://cloud.githubusercontent.com/assets/5586135/5718998/3cace868-9b1c-11e4-966a-42194d0f29e3.png)

**Comment by Stibbons** [comment] 2015-01-13 10:38
that's wierd...

**Comment by manoevis** [comment] 2015-01-13 10:42
Yep. How could I investigate it? To see which variables is used or smth?

**Comment by Stibbons** [comment] 2015-01-13 10:45
I wonder if this doesn't comes from python-vte which reach weirdly on some even. The code is in python and pretty easy to read, there are already some debug code, maybe you can add current top line number to see when it changes.... I don't have this issue on my system (ubuntu)...

**Comment by manoevis** [comment] 2015-01-13 12:18
can't find phyton-vte in fedora, though this issue was on ubuntu also, as I mentioned.

**Comment by Stibbons** [comment] 2015-01-13 12:25
apt-get install python-vte

if you use guake, you have this packet installed on your system (it's a dependency)

**Comment by manoevis** [comment] 2015-01-13 12:38
yes, there is dependency called vte, but with no python files:

/usr/lib64/libvte.so.9
/usr/lib64/libvte.so.9.2800.2
/usr/lib64/python2.7/site-packages/gtk-2.0
/usr/lib64/python2.7/site-packages/gtk-2.0/vtemodule.so
/usr/lib64/vte
/usr/lib64/vte/gnome-pty-helper

**Comment by manoevis** [comment] 2015-02-12 06:07
![guake_main_w_option](https://cloud.githubusercontent.com/assets/5586135/6162560/facb2f8e-b28d-11e4-86bc-f239b07ad739.png)

^ if I set this option (slightly set to left) then works fine, but if I set this option a bit more (slightly to right) then things are messed up as mentioned above.

**Comment by dark-rabbit** [comment] 2015-03-01 02:04
I can confirm this issue with guake 0.5.2-1 on archlinux using gnome. This happens only when main window height is set at 100%.

**Comment by dark-rabbit** [comment] 2015-03-01 02:30
It's also the case in fullscreen mode, it can become a real problem with vim which crashes after few hide/show

**Comment by nilehmann** [comment] 2015-04-14 14:11
I have the same issue in archlinu with gnome.

**Comment by Vizzard** [comment] 2015-05-05 06:23
I can confirm this issue in guake 0.7.0 on Ubuntu 14.10 x64. After clearing terminal then hide and show it gives empty terminal. Prompt is usually few lines up. But I don't have it when using fullscreen. I use guake 100% height and 100% width. Then I have it.

**Comment by manoevis** [comment] 2015-05-05 06:54
I have the same @Vizzard with Ubuntu 15.04 x64 and guake 0.7.0. When I set 97% for height it does not scrolls up, though. But width is set to 100% and it does not scales properly.

**Comment by Bubu** [comment] 2016-09-18 08:37
For some reason I now have this problem after upgrading form Xubuntu 14.04 to 16.04

Guake is the same version 0.8.7

It is at least temporarily fixed after fiddling with main window height und fullscreen settings.
I will keep an I on this.

**Comment by jamb0ss** [comment] 2016-10-03 03:57
any workaround?

**Comment by robertfoss** [comment] 2016-10-27 00:00
I'm having this issue too.

**Comment by fprawits** [comment] 2016-10-30 13:41
Having this issue too on Ubuntu 16.04 with curently latest guake version 0.8.7. See also the follwing threads which all seem to be duplicates of this one:
[#832](https://github.com/Guake/guake/issues/832) opened by me, also some debug messages can be found here
[#784](https://github.com/Guake/guake/issues/784)
[#438](https://github.com/Guake/guake/issues/438)

**Comment by fievelk** [comment] 2016-11-19 15:17
I have the same issue using xubuntu 16.04.

**Comment by robertfoss** [comment] 2016-11-19 15:19
The terminal receiving funny characters over for example serial seems to
also do it in.

**Comment by lokeshthegenius** [comment] 2016-12-18 18:23
having same issue

**Comment by Stibbons** [comment] 2016-12-21 09:58
yes, we are rewriting everything !

**Comment by sshishov** [comment] 2017-01-25 05:45
@Stibbons when approximately we can expect the release of rewritten `guake`? Thanks!

**Comment by mouseratti** [comment] 2017-01-28 06:47
I hope in next 4-6 month. Main window is already finished, we need to implement settings & menus.

**Comment by sshishov** [comment] 2017-01-29 06:39
@mouseratti Cool, sounds great! Do you need some help, I am Python developer myself, but mainly work with Django though.

**Comment by mouseratti** [comment] 2017-01-30 00:12
yes, we need. I'm going to create couple of subtasks this week. You can get some.

**Comment by sshishov** [comment] 2017-01-30 06:00
Ok. Could you pint me out these subtasks after you create them and I will fork and implement.

**Comment by Davidy22** [comment] 2021-09-16 23:05
A rewrite was done, issue no longer appears to occur and no reports submitted since the rewrite, closing.

**Closed by Davidy22** 2021-09-16 23:05 UTC
Labels: Type: Defect, Priority: High
