### ISSUE TITLE
Unable to bind any hotkey under GNOME/Wayland

### ISSUE THREAD

**Issue by jnsnow** [Guake/guake#1642] opened 2019-09-05 18:17 UTC
I am using guake 3.6.3 on Fedora 30 under GNOME with Wayland.

When guake starts up, it renders the message "A problem happened when binding F12 key." and encourages me to pick a different key. The problem is that NO key appears to take at all, so I cannot toggle visibility.

This seems even worse than it used to be; where the hotkey would bind but would simply not work on wayland rendered windows.

I've tried completely resetting all gnome settings, guake settings, etc.

**Expected behavior**

I should be able to use a hotkey to open guake.

**Actual behavior**

No hotkey will bind. No key will toggle guake.

**To Reproduce**

I don't know. I'm using Fedora 30 as close to a vanilla configuration as I know how to create.

-------------------------------------------------------------------------------

<details><summary>$ guake --support</summary>

Guake Version:		3.6.3

Vte Version:		0.56.3

Vte Runtime Version:	0.56.3

--------------------------------------------------
GTK+ Version:		3.24.10

GDK Backend:		__gi__.GdkWaylandDisplay

--------------------------------------------------
Desktop Session: gnome

--------------------------------------------------
Display: wayland-0

RGBA visual: True

Composited: True

* Monitor: 0 - CMN 0x14b1
    * Geometry:		1920 x 1080 at 3840, 0
    * Size:		310 x 170 mm²
    * Primary:		False
    * Refresh rate:	60.01 Hz
    * Subpixel layout:	unknown
* Monitor: 1 - ACI VE247
    * Geometry:		1920 x 1080 at 1920, 0
    * Size:		530 x 300 mm²
    * Primary:		False
    * Refresh rate:	60.00 Hz
    * Subpixel layout:	unknown
* Monitor: 2 - ACI VE247
    * Geometry:		1920 x 1080 at 0, 0
    * Size:		530 x 300 mm²
    * Primary:		False
    * Refresh rate:	60.00 Hz
    * Subpixel layout:	unknown

**Comment by jnsnow** [comment] 2019-09-05 18:48
When running in verbose mode, I see messages like this:
```
reload_global: 'F10'

** (guake:15653): WARNING **: 14:31:54.045: Binding 'F10' failed!
can't bind show-focus key
```

I wanted to see what was going wrong, so I decided to track this along...

```
bash-5.0$ python3
Python 3.7.4 (default, Jul  9 2019, 16:32:37) 
[GCC 9.1.1 20190503 (Red Hat 9.1.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gi
>>> gi.require_version('Keybinder', '3.0')
>>> from gi.repository import Keybinder
>>> 
>>> Keybinder.init()

(process:15987): Gdk-CRITICAL **: 14:40:18.287: gdk_keymap_get_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(process:15987): Gdk-CRITICAL **: 14:40:18.287: gdk_screen_get_root_window: assertion 'GDK_IS_SCREEN (screen)' failed
```

Well, that doesn't look good.

```
>>> Keybinder.bind('F12', lambda: print("Hello World! Hotkey Pressed!"))

(process:15987): Gdk-CRITICAL **: 14:42:50.108: gdk_screen_get_root_window: assertion 'GDK_IS_SCREEN (screen)' failed

(process:15987): Gdk-CRITICAL **: 14:42:50.108: gdk_keymap_get_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
False
```

That doesn't look so good either.

**Comment by jnsnow** [comment] 2019-09-05 23:48
I guess this is due to wayland not supporting hotkeys, so keybinder won't work at all anymore unless you are using XWayland, which is apparently not the case for F30, gnome and gtk3 apps now. 

That's my understanding right now, anyway.

**Comment by j-frost** [comment] 2019-09-07 14:57
I believe I have a similar issue. After updating my system I now get errors when starting up Guake that complain about not being able to bind my "Toggle Guake" hotkey (in my case, that's super+enter). 

```<details><summary>$ guake --support</summary>

Guake Version:		3.6.3

Vte Version:		0.56.3

Vte Runtime Version:	0.56.3

--------------------------------------------------
GTK+ Version:		3.24.11

GDK Backend:		GdkX11.X11Display

--------------------------------------------------
Desktop Session: gnome

--------------------------------------------------
Display: :0

RGBA visual: True

Composited: True

* Monitor: 0 -  XWAYLAND0
    * Geometry:		1280 x 720 % 2 at 0, 0
    * Size:		310 x 170 mm²
    * Primary:		True
    * Refresh rate:	59.96 Hz
    * Subpixel layout:	unknown
```

**Comment by j-frost** [comment] 2019-09-07 14:59
Workaround I stole from #1340 : I've bound super+enter to just "guake" in Gnome.

**Comment by jnsnow** [comment] 2019-09-07 15:27
So, two things:

1. If quake is running under XWayland, it probably ought to warn the user that hotkey support will only work sporadically. I.e., it will not work if any Wayland window has focus. Bonus points if it links to a github issue url in the console.

2. If guake is itself running under Wayland, it should disable global hotkey bindings *entirely* as they will not work under any circumstance. A message akin to "Global hotkeys not presently available under Wayland" would at least reduce user confusion.

I suppose the only path forward right now is to wait for GNOME to offer a hotkey binding service under wayland.

**Comment by jnsnow** [comment] 2019-09-08 16:35
I went through about the first seven pages of issues (Back to about ~900):

These are all effectively duplicates for the "Wayland Hotkey Bug":
#1640 
#1448 
#1041 
#911 
#492 

There are some RFEs on how to remedy it:
#1343 
#914 

Various other hotkey issues that are not necessarily related:
1076, 1638, 1591, 1644, 1416

@gsemet Would you like assistance with github issue triage? I'm willing to spend some time trying to clean up the issue tracker.

**Comment by gsemet** [comment] 2019-09-08 16:42
Hi. Thanks. No pbl, if you want to be able to do a little bit of triage. Not enough time from my side to do this. I never used wayland so it is very difficult for me to debug anything related to it. So appart from documenting the work arround, there is no much what I can do.

Just go in the ticket and @gsemet me in the ticket you want me to update. If you do good job I'll give you the permission to do it on your own :)

**Comment by varantes-cit** [comment] 2019-09-27 18:43
So, I'm having the same issue here.
Is this a Won't Fix for real?

Asking because here I cannot open Guake anymore (I cannot bind any key to do that). It will be very hard to keep working with Guake this way. =/

```
Guake Version:		3.6.3

Vte Version:		0.52.2

Vte Runtime Version:	0.52.2

--------------------------------------------------
GTK+ Version:		3.22.30

GDK Backend:		GdkX11.X11Display

--------------------------------------------------
Desktop Session: ubuntu-wayland

--------------------------------------------------
Display: :0

RGBA visual: True

Composited: True

* Monitor: 0 -  XWAYLAND0
    * Geometry:		1366 x 768 at 0, 0
    * Size:		310 x 170 mm²
    * Primary:		True
    * Refresh rate:	59.98 Hz
    * Subpixel layout:	unknown
* Monitor: 1 -  XWAYLAND1
    * Geometry:		2560 x 1440 at 1366, 0
    * Size:		550 x 310 mm²
    * Primary:		False
    * Refresh rate:	59.91 Hz
    * Subpixel layout:	unknown

```

**Comment by Isashi** [comment] 2019-10-01 06:26
As suggested by @aurora-of-earth in #1640, under GNOME you can use the following workaround.
I tried it and in my case it works perfectly. 

> @Isashi Guake doesn't support wayland very well, there's no problem with GNOME; You'll have the same sort of issue on KDE Plasma or any other desktop environment.
> To fix this:
> 
> * Remove the guake shortcut from inside of guake itself, if you've set it there at all.
> * Go to GNOME's Settings > Devices > Keyboard
> * Scroll down the screen and add a custom shortcut.(put 'guake' in the 'Command' field)

**Comment by j-frost** [comment] 2019-10-01 09:09
The workaround works well in single monitor setups. Has varying issues when your active display is not 0 or main though...

**Comment by srados** [comment] 2019-10-04 11:38
Had the same problem on ubuntu 19.10, did like descibed in https://github.com/Guake/guake/issues/1640, works fine now

**Comment by Isashi** [comment] 2019-11-04 10:28
Solution in #1640 is not valid in Fedora 31 (show: works properly / hide: glitch, often the terminal disappear and re-appear)

**Comment by mumrau** [comment] 2019-11-10 10:34
This needs to be fixed as it really diminishes the seamless usage of `guake` which is a must-have on any of my installations...
The most frustrating thing is that on the computers that I didn't install in Fedora 31 but upgraded from 29 to 30 and then 31, my keybinding is working absolutely flawlessy. Makes me wonder whether I should install an old fedora and proceed with upgrades...

**Comment by gsemet** [comment] 2019-11-10 10:50
Pull request welcome. I do not use wayland so I cannot test anything :(

**Comment by mrshu** [comment] 2020-01-03 08:41
I believe it is simply not possible to bind hotkeys on Wayland. This seems to be seen as a security precaution (see https://github.com/albertlauncher/albert/issues/309 for a longer discussion).

It seems the best thing to do for now would be to show some note to Wayland users (potentially with a link to one of the related issues) and invest into implementing the GAction mentioned in #1343.

**Comment by Isashi** [comment] 2020-01-03 11:20
(at least) in Fedora 31, a possible wordaround, is to simply use xorg instead of wayland clicking on the gear icon before login

**Comment by rmeissn** [comment] 2020-01-31 10:03
I'm having the same problem running Fedora 31 on Wayland.
A good workaround is descibed by:

> As suggested by @aurora-of-earth in #1640, under GNOME you can use the following workaround.
> I tried it and in my case it works perfectly.
> 
> > @Isashi Guake doesn't support wayland very well, there's no problem with GNOME; You'll have the same sort of issue on KDE Plasma or any other desktop environment.
> > To fix this:
> > 
> > * Remove the guake shortcut from inside of guake itself, if you've set it there at all.
> > * Go to GNOME's Settings > Devices > Keyboard
> > * Scroll down the screen and add a custom shortcut.(put 'guake' in the 'Command' field)

but I want to change it a little: Add guake to autostart on login and use `guake-toggle` for the keyboard-shortcut (gnome settings).
The only annoying thing is that I'm unable to delete the toggle visibility shortcut in guake's settings itself, thus it's always printing the error message about binding the key on startup of the system.
Is there a way to get rid of this notification?

**Comment by iMartyn** [comment] 2020-02-28 10:55
@j-frost and others in the thread with the same issue - the monitor problems are a separate issue.  `guake-toggle` should do exactly what the hotkey does, unfortunately there was a bug in 3.4.x, which was fixed in 3.5.0 and above so either upgrade / install with pip or apply the patch in #1450 to fix the mouse problem.

I can confirm that with 3.7.0 installed via `pip3 install --user guake` on debian works flawlessly with multi-monitor wayland and the workaround.

**Comment by gebau00a** [comment] 2020-08-19 05:07
> I'm having the same problem running Fedora 31 on Wayland.
> A good workaround is descibed by:
> 
> > @Isashi Guake doesn't support wayland very well, there's no problem with GNOME; You'll have the same sort of issue on KDE Plasma or any other desktop environment.
> > To fix this:
> > 
> > * Remove the guake shortcut from inside of guake itself, if you've set it there at all.
> > * Go to GNOME's Settings > Devices > Keyboard
> > * Scroll down the screen and add a custom shortcut.(put 'guake' in the 'Command' field)
> 
> but I want to change it a little:
> 
> * add guake to autostart on login
> * use `guake-toggle` for the keyboard-shortcut in gnome settings
> 
> The only annoying thing is that I'm unable to delete the toggle visibility shortcut in guake's settings itself, thus it's notifying me about being unable to bind the key on startup of the system.
> Is there a way to get rid of this notification?

You can use dconf-editor, apps/guake/keybindings/global/show-hide and set custom value to empty string.

**Comment by zevdg** [comment] 2020-08-30 19:18
> You can use dconf-editor, apps/guake/keybindings/global/show-hide and set custom value to empty string.

Setting it to empty string didn't work for me, but setting it to `disabled` did ([source](https://github.com/Guake/guake/blob/3ac1a69660d6b2e3dcf0fb2edf6a308cd0e9a3b4/guake/keybindings.py#L110)).

**Comment by gpeal** [comment] 2020-11-05 16:30
One problem with the settings approach is that if you have "hide on lose focus checked", pressing the hotkey hides guake instead of makes it visible if it is on screen but not focused. It then requires a second key press to show it again.

**Comment by CyborTronik** [comment] 2021-06-05 11:49
An workaround that works in Fedora 34: 
Go to System Settings - Keyboard -> Keyboard Shortcut section -> Customize Shortcuts -> Custom Shortcuts -> Press + -> put any name, command `guake`, set key 'F12'

**Comment by msdrigg** [comment] 2021-06-21 16:10
Here's a simple bash script you can add to your F-12 gnome keyboard shortcut.

It handles the case where guake is not already open and opens it. Otherwise it just toggles it.

```bash
# guake-toggle only prints to stdout if guake is active  
if [ "$(guake-toggle)" == "" ]; then    
    # If guake isn't running, start it  
    guake &  
    # Also run guake-toggle with a delay to open guake  
    sleep 0.5;     
    guake-toggle;  
fi  
```

**Comment by staticdev** [comment] 2021-06-30 12:00
@zevdg @gpeal one solution that fixed for me and don't need an extra key is adding with dconf an extra keybinding for guake-toggle. I also made an ansible script for that:

```yaml
- name: Add keybinding for Guake in Wayland
  dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
  with_items:
    # values from gsettings list-recursively /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings
    - key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings"
      value: ["/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/guake/"]
    - key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/guake/binding"
      value: "'{{ guake_keybinding }}'"
    - key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/guake/command"
      value: "'/usr/bin/guake-toggle'"
    - key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/guake/name"
      value: "'Guake'"
```

Ideally, guake could detect it is running on Wayland and manage himself custom keybindings.

**Comment by Jeansen** [comment] 2021-12-17 22:53
> * Remove the guake shortcut from inside of guake itself, if you've set it there at all.
> * Go to GNOME's Settings > Devices > Keyboard
> * Scroll down the screen and add a custom shortcut.(put 'guake' in the 'Command' field)

This did the trick for me! :smile:

**Comment by Pysis868** [comment] 2021-12-21 17:44
Same, distressing to see the years-long issue that may be specific to Wayland and needs the externally-bound `guake-toggle` workaround solution.

I think #1941 and #1942 only made some small changes, not the keybindings system re-implementation or other large changes that may have been mentioned elsewhere.

What's strange is I was customizing keyboard shortcuts in GNOME along with this application, and they were all working before some system updates where I'm sure a bunch of packages changed, also including kernel patch version updates, but were only done days apart from a fresh installation a week or 2 ago.  I have not performed other serious system changes like at the login screen changing the display server (protocol?) from Wayland to Xorg, or similar through user login shell environment variable changes either.  Only messing with NVIDIA drivers where the latest was visually buggy.

Just a note the relevant code using GTK bind is here:
https://github.com/Guake/guake/blob/a084a1d0d11d2306ca5447c2cfaf31db0393c798/guake/keybindings.py#L211

I had started to investigate the issue from pages like this one: https://askubuntu.com/questions/1128705/keyboard-shortcut-get-a-list-of-what-is-already-used

My system info:
Fedora 35 Workstation
Installed Guake through the default software catalog.

```
<details><summary>$ guake --support</summary>
Guake Version:		3.7.0
Vte Version:		0.66.1
Vte Runtime Version:	0.66.1
--------------------------------------------------
GTK+ Version:		3.24.30
GDK Backend:		__gi__.GdkWaylandDisplay
--------------------------------------------------
Desktop Session: gnome
--------------------------------------------------
Display: wayland-0
RGBA visual: True
Composited: True
```

**Comment by samtuke** [comment] 2021-12-27 01:26
I seem to have this issue too. Gnome shortcuts don't list the key combo I want for Guake (`shift+ctrl`). This is a fresh install, but Guake says the keys are in use.

**Comment by Davidy22** [comment] 2021-12-27 02:50
The changes in #1941 fairly hefty and addressed something completely unrelated to this issue.

Preventing programs from being able to pick up keyboard input when the program is not running is a "feature" of Wayland, binding `guake-toggle` using the system wide keyboard shortcut utility is the accepted solution, not a workaround. A workaround would be figuring out a way to defy the intentional limitation set out in the Wayland specification. Switched to wayland a few weeks ago so I could finally get first hand experience with the wayland related issues and this issue is solved by going into settings->keyboard shortcuts and binding a custom shortcut to `guake-toggle`. Guake still has the entry listed in the keyboard shortcuts menu for the users still on X11, but wayland will intentionally disregard it.

**Closed by Davidy22** 2021-12-27 02:50 UTC
Labels: Priority: Low, Env: Wayland

**Comment by Davidy22** [comment] 2022-01-27 02:42
Issue #2011 has been created to put first-time configuration for this on the to-do list
