### ISSUE TITLE
Installation failed - No module named vte 

### ISSUE THREAD

**Issue by Zygonie** [Guake/guake#883] opened 2017-01-04 14:39 UTC
I tried to install version 0.8.8 and version 0.5.0 on Mint 17.3 but I always got this error 
```bash
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for DEPENDENCIES... yes
checking for the python-vte package... no
configure: error: cannot import Python module "vte".
    Please check if you have python-vte installed. The error was:
    No module named vte
make: *** No targets specified and no makefile found.  Stop.
```

However, python-vte is installed
```bash
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-vte is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

I also tried to reinstall python-vte, but it keeps failing

**Comment by Stibbons** [comment] 2017-01-04 16:25
To compile you need to install the `-dev` package

**Comment by Zygonie** [comment] 2017-01-04 17:01
python-dev package is also installed

**Comment by Stibbons** [comment] 2017-01-04 17:40
`python-vte-dev` ?

**Comment by Zygonie** [comment] 2017-01-04 18:10
Same error :(

**Comment by Bedotech** [comment] 2017-03-08 15:21
Same problem here in pyen environment `2.7.13` i can't install guake from master on Ubuntu Mate 16.04 it stop me with this message:
```
configure: error: cannot import Python module "vte".
    Please check if you have python-vte installed. The error was:
    No module named vte
make: *** No targets specified and no makefile found.  Stop.
```

But the package `python-vte` and `python-vte-dev` is installed

**Comment by yubeic** [comment] 2017-05-28 04:52
This is probably because your default python is not the native ubuntu python.
 Please try to find out this by: which python
My guess is that you are using anaconda or so.
In order to solve this problem you can temporally change the priority of ubuntu python by:
export PATH="/usr/bin:$PATH"
Now, you can verify that vte module exists by: import vte in python
And you should be able to install guake too if nothing else is wrong.
Then after you finish installing guake, you also have to modify the guake script /usr/local/share/bin/gauke to make sure that the python it's using is /usr/bin/python. Otherwise, if you close this terminal, the next time the guake terminal will use your default python again.
I hope this helps.

**Comment by Ozzyboshi** [comment] 2018-01-19 15:51
I had a similar issue (see #1077) I solved with sudo apt-get install gir1.2-vte-2.91, dont know if it will work for you, I am on Debian 9

**Comment by Stibbons** [comment] 2018-01-19 17:34
I close this ticker since the issue is from your environment. You should make sure guake starts with the python 3 of your system. I have updated the readme

**Closed by Stibbons** 2018-01-19 17:34 UTC
