### ISSUE TITLE
Nano does not behave as expected in Guake terminal.

### ISSUE THREAD

**Issue by ykartal** [Guake/guake#704] opened 2016-02-03 22:12 UTC
I am using Centos Release 6.7 and installed Guake.
But when type nano <filename> on guake terminal, it is not possible to modify content or doing anything because a black empty screen is opened though there are texts in file.

Any idea?

**Comment by Stibbons** [comment] 2016-02-04 13:56
Don't have this problem under ubuntu and 0.8.4

**Comment by ykartal** [comment] 2016-02-27 23:33
As below image, guake shows nothing after the below command run
`nano install_chrome.sh`
PS: Take care of the right bottom of the screen

![Image of Guake]
(http://i.imgur.com/yEko0nl.png)

**Comment by Davidy22** [comment] 2021-09-16 22:42
Unable to reproduce, does this still occur for you?

**Comment by Davidy22** [comment] 2022-04-21 12:26
Closing due to no reply, reopen if still relevant

**Closed by Davidy22** 2022-04-21 12:26 UTC
Labels: Type: Defect, Priority: Low
