### ISSUE TITLE
Makefile, line 109

### ISSUE THREAD

**Issue by MyrikLD** [Guake/guake#1293] opened 2018-04-18 13:39 UTC
"$(DESTDIR)$(prefix)/share/applications/guake.desktop" == "//usr/local/share/applications/guake.desktop"

**Comment by gsemet** [comment] 2018-04-18 14:27
yes, so ? The problem is the leading double "/" ?

**Comment by arvin-foroutan** [comment] 2018-04-19 12:41
This just became a problem for me also.

Edited the Makefile temporarily to get it to install until it's fixed and all is well now.

```
diff --git a/Makefile b/Makefile
index 09880da..91dd70d 100644
--- a/Makefile
+++ b/Makefile
@@ -109,9 +109,9 @@ install-schemas:
        install -Dm644 "$(DEV_DATA_DIR)/guake.desktop" "$(DESTDIR)$(prefix)/share/applications/guake.desktop"
        install -Dm644 "$(DEV_DATA_DIR)/guake-prefs.desktop" "$(DESTDIR)$(prefix)/share/applications/guake-prefs.desktop"
        mkdir -p $(DESTDIR)$(IMAGE_DIR)
-       install -Dm644 $(DEV_DATA_DIR)/pixmaps/*.png "$(DESTDIR)$(prefix)$(IMAGE_DIR)/"
-       install -Dm644 $(DEV_DATA_DIR)/pixmaps/*.svg "$(DESTDIR)$(prefix)$(IMAGE_DIR)/"
-       install -Dm644 $(DEV_DATA_DIR)/pixmaps/guake.png "$(DESTDIR)$(prefix)/share/pixmaps/guake.png"
+       install -Dm644 $(DEV_DATA_DIR)/pixmaps/*.png "$(DESTDIR)$(IMAGE_DIR)/"
+       install -Dm644 $(DEV_DATA_DIR)/pixmaps/*.svg "$(DESTDIR)$(IMAGE_DIR)/"
+       install -Dm644 $(DEV_DATA_DIR)/pixmaps/guake.png "$(DESTDIR)/share/pixmaps/guake.png"
        mkdir -p $(DESTDIR)$(SHARE_DIR)
        mkdir -p $(DESTDIR)$(GLADE_DIR)
        install -Dm644  $(DEV_DATA_DIR)/*.glade "$(DESTDIR)$(GLADE_DIR)"
```

**Comment by gsemet** [comment] 2018-04-19 14:00
fixed on HEAD

**Closed by gsemet** 2018-04-19 14:00 UTC
